// Code generated by ent, DO NOT EDIT.

package rlsrule

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rlsrule type in the database.
	Label = "rls_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTargetTable holds the string denoting the target_table field in the database.
	FieldTargetTable = "target_table"
	// FieldSQLPredicate holds the string denoting the sql_predicate field in the database.
	FieldSQLPredicate = "sql_predicate"
	// EdgeDataset holds the string denoting the dataset edge name in mutations.
	EdgeDataset = "dataset"
	// Table holds the table name of the rlsrule in the database.
	Table = "rls_rules"
	// DatasetTable is the table that holds the dataset relation/edge.
	DatasetTable = "rls_rules"
	// DatasetInverseTable is the table name for the Dataset entity.
	// It exists in this package in order to avoid circular dependency with the "dataset" package.
	DatasetInverseTable = "datasets"
	// DatasetColumn is the table column denoting the dataset relation/edge.
	DatasetColumn = "dataset_rls_rules"
)

// Columns holds all SQL columns for rlsrule fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTargetTable,
	FieldSQLPredicate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "rls_rules"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"dataset_rls_rules",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the RlsRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTargetTable orders the results by the target_table field.
func ByTargetTable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetTable, opts...).ToFunc()
}

// BySQLPredicate orders the results by the sql_predicate field.
func BySQLPredicate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSQLPredicate, opts...).ToFunc()
}

// ByDatasetField orders the results by dataset field.
func ByDatasetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDatasetStep(), sql.OrderByField(field, opts...))
	}
}
func newDatasetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DatasetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DatasetTable, DatasetColumn),
	)
}
