// Code generated by ent, DO NOT EDIT.

package rlsrule

import (
	"bi-metadata/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEQ(FieldName, v))
}

// TargetTable applies equality check predicate on the "target_table" field. It's identical to TargetTableEQ.
func TargetTable(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEQ(FieldTargetTable, v))
}

// SQLPredicate applies equality check predicate on the "sql_predicate" field. It's identical to SQLPredicateEQ.
func SQLPredicate(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEQ(FieldSQLPredicate, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldContainsFold(FieldName, v))
}

// TargetTableEQ applies the EQ predicate on the "target_table" field.
func TargetTableEQ(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEQ(FieldTargetTable, v))
}

// TargetTableNEQ applies the NEQ predicate on the "target_table" field.
func TargetTableNEQ(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldNEQ(FieldTargetTable, v))
}

// TargetTableIn applies the In predicate on the "target_table" field.
func TargetTableIn(vs ...string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldIn(FieldTargetTable, vs...))
}

// TargetTableNotIn applies the NotIn predicate on the "target_table" field.
func TargetTableNotIn(vs ...string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldNotIn(FieldTargetTable, vs...))
}

// TargetTableGT applies the GT predicate on the "target_table" field.
func TargetTableGT(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldGT(FieldTargetTable, v))
}

// TargetTableGTE applies the GTE predicate on the "target_table" field.
func TargetTableGTE(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldGTE(FieldTargetTable, v))
}

// TargetTableLT applies the LT predicate on the "target_table" field.
func TargetTableLT(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldLT(FieldTargetTable, v))
}

// TargetTableLTE applies the LTE predicate on the "target_table" field.
func TargetTableLTE(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldLTE(FieldTargetTable, v))
}

// TargetTableContains applies the Contains predicate on the "target_table" field.
func TargetTableContains(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldContains(FieldTargetTable, v))
}

// TargetTableHasPrefix applies the HasPrefix predicate on the "target_table" field.
func TargetTableHasPrefix(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldHasPrefix(FieldTargetTable, v))
}

// TargetTableHasSuffix applies the HasSuffix predicate on the "target_table" field.
func TargetTableHasSuffix(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldHasSuffix(FieldTargetTable, v))
}

// TargetTableEqualFold applies the EqualFold predicate on the "target_table" field.
func TargetTableEqualFold(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEqualFold(FieldTargetTable, v))
}

// TargetTableContainsFold applies the ContainsFold predicate on the "target_table" field.
func TargetTableContainsFold(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldContainsFold(FieldTargetTable, v))
}

// SQLPredicateEQ applies the EQ predicate on the "sql_predicate" field.
func SQLPredicateEQ(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEQ(FieldSQLPredicate, v))
}

// SQLPredicateNEQ applies the NEQ predicate on the "sql_predicate" field.
func SQLPredicateNEQ(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldNEQ(FieldSQLPredicate, v))
}

// SQLPredicateIn applies the In predicate on the "sql_predicate" field.
func SQLPredicateIn(vs ...string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldIn(FieldSQLPredicate, vs...))
}

// SQLPredicateNotIn applies the NotIn predicate on the "sql_predicate" field.
func SQLPredicateNotIn(vs ...string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldNotIn(FieldSQLPredicate, vs...))
}

// SQLPredicateGT applies the GT predicate on the "sql_predicate" field.
func SQLPredicateGT(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldGT(FieldSQLPredicate, v))
}

// SQLPredicateGTE applies the GTE predicate on the "sql_predicate" field.
func SQLPredicateGTE(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldGTE(FieldSQLPredicate, v))
}

// SQLPredicateLT applies the LT predicate on the "sql_predicate" field.
func SQLPredicateLT(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldLT(FieldSQLPredicate, v))
}

// SQLPredicateLTE applies the LTE predicate on the "sql_predicate" field.
func SQLPredicateLTE(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldLTE(FieldSQLPredicate, v))
}

// SQLPredicateContains applies the Contains predicate on the "sql_predicate" field.
func SQLPredicateContains(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldContains(FieldSQLPredicate, v))
}

// SQLPredicateHasPrefix applies the HasPrefix predicate on the "sql_predicate" field.
func SQLPredicateHasPrefix(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldHasPrefix(FieldSQLPredicate, v))
}

// SQLPredicateHasSuffix applies the HasSuffix predicate on the "sql_predicate" field.
func SQLPredicateHasSuffix(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldHasSuffix(FieldSQLPredicate, v))
}

// SQLPredicateEqualFold applies the EqualFold predicate on the "sql_predicate" field.
func SQLPredicateEqualFold(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldEqualFold(FieldSQLPredicate, v))
}

// SQLPredicateContainsFold applies the ContainsFold predicate on the "sql_predicate" field.
func SQLPredicateContainsFold(v string) predicate.RlsRule {
	return predicate.RlsRule(sql.FieldContainsFold(FieldSQLPredicate, v))
}

// HasDataset applies the HasEdge predicate on the "dataset" edge.
func HasDataset() predicate.RlsRule {
	return predicate.RlsRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DatasetTable, DatasetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDatasetWith applies the HasEdge predicate on the "dataset" edge with a given conditions (other predicates).
func HasDatasetWith(preds ...predicate.Dataset) predicate.RlsRule {
	return predicate.RlsRule(func(s *sql.Selector) {
		step := newDatasetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RlsRule) predicate.RlsRule {
	return predicate.RlsRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RlsRule) predicate.RlsRule {
	return predicate.RlsRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RlsRule) predicate.RlsRule {
	return predicate.RlsRule(sql.NotPredicates(p))
}
