// Code generated by ent, DO NOT EDIT.

package chart

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the chart type in the database.
	Label = "chart"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldColumnStyles holds the string denoting the column_styles field in the database.
	FieldColumnStyles = "column_styles"
	// EdgeDataset holds the string denoting the dataset edge name in mutations.
	EdgeDataset = "dataset"
	// EdgeDashboards holds the string denoting the dashboards edge name in mutations.
	EdgeDashboards = "dashboards"
	// Table holds the table name of the chart in the database.
	Table = "charts"
	// DatasetTable is the table that holds the dataset relation/edge.
	DatasetTable = "charts"
	// DatasetInverseTable is the table name for the Dataset entity.
	// It exists in this package in order to avoid circular dependency with the "dataset" package.
	DatasetInverseTable = "datasets"
	// DatasetColumn is the table column denoting the dataset relation/edge.
	DatasetColumn = "dataset_charts"
	// DashboardsTable is the table that holds the dashboards relation/edge. The primary key declared below.
	DashboardsTable = "chart_dashboards"
	// DashboardsInverseTable is the table name for the Dashboard entity.
	// It exists in this package in order to avoid circular dependency with the "dashboard" package.
	DashboardsInverseTable = "dashboards"
)

// Columns holds all SQL columns for chart fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldConfig,
	FieldColumnStyles,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "charts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"dataset_charts",
}

var (
	// DashboardsPrimaryKey and DashboardsColumn2 are the table columns denoting the
	// primary key for the dashboards relation (M2M).
	DashboardsPrimaryKey = []string{"chart_id", "dashboard_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Chart queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDatasetField orders the results by dataset field.
func ByDatasetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDatasetStep(), sql.OrderByField(field, opts...))
	}
}

// ByDashboardsCount orders the results by dashboards count.
func ByDashboardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDashboardsStep(), opts...)
	}
}

// ByDashboards orders the results by dashboards terms.
func ByDashboards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDashboardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDatasetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DatasetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DatasetTable, DatasetColumn),
	)
}
func newDashboardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DashboardsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, DashboardsTable, DashboardsPrimaryKey...),
	)
}
