// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/chart"
	"bi-metadata/ent/dashboard"
	"bi-metadata/ent/dataset"
	"bi-metadata/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChartUpdate is the builder for updating Chart entities.
type ChartUpdate struct {
	config
	hooks    []Hook
	mutation *ChartMutation
}

// Where appends a list predicates to the ChartUpdate builder.
func (_u *ChartUpdate) Where(ps ...predicate.Chart) *ChartUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ChartUpdate) SetTitle(v string) *ChartUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ChartUpdate) SetNillableTitle(v *string) *ChartUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ChartUpdate) SetConfig(v map[string]interface{}) *ChartUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetColumnStyles sets the "column_styles" field.
func (_u *ChartUpdate) SetColumnStyles(v map[string]interface{}) *ChartUpdate {
	_u.mutation.SetColumnStyles(v)
	return _u
}

// SetDatasetID sets the "dataset" edge to the Dataset entity by ID.
func (_u *ChartUpdate) SetDatasetID(id int) *ChartUpdate {
	_u.mutation.SetDatasetID(id)
	return _u
}

// SetNillableDatasetID sets the "dataset" edge to the Dataset entity by ID if the given value is not nil.
func (_u *ChartUpdate) SetNillableDatasetID(id *int) *ChartUpdate {
	if id != nil {
		_u = _u.SetDatasetID(*id)
	}
	return _u
}

// SetDataset sets the "dataset" edge to the Dataset entity.
func (_u *ChartUpdate) SetDataset(v *Dataset) *ChartUpdate {
	return _u.SetDatasetID(v.ID)
}

// AddDashboardIDs adds the "dashboards" edge to the Dashboard entity by IDs.
func (_u *ChartUpdate) AddDashboardIDs(ids ...int) *ChartUpdate {
	_u.mutation.AddDashboardIDs(ids...)
	return _u
}

// AddDashboards adds the "dashboards" edges to the Dashboard entity.
func (_u *ChartUpdate) AddDashboards(v ...*Dashboard) *ChartUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDashboardIDs(ids...)
}

// Mutation returns the ChartMutation object of the builder.
func (_u *ChartUpdate) Mutation() *ChartMutation {
	return _u.mutation
}

// ClearDataset clears the "dataset" edge to the Dataset entity.
func (_u *ChartUpdate) ClearDataset() *ChartUpdate {
	_u.mutation.ClearDataset()
	return _u
}

// ClearDashboards clears all "dashboards" edges to the Dashboard entity.
func (_u *ChartUpdate) ClearDashboards() *ChartUpdate {
	_u.mutation.ClearDashboards()
	return _u
}

// RemoveDashboardIDs removes the "dashboards" edge to Dashboard entities by IDs.
func (_u *ChartUpdate) RemoveDashboardIDs(ids ...int) *ChartUpdate {
	_u.mutation.RemoveDashboardIDs(ids...)
	return _u
}

// RemoveDashboards removes "dashboards" edges to Dashboard entities.
func (_u *ChartUpdate) RemoveDashboards(v ...*Dashboard) *ChartUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDashboardIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChartUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChartUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChartUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChartUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ChartUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(chart.Table, chart.Columns, sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(chart.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(chart.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ColumnStyles(); ok {
		_spec.SetField(chart.FieldColumnStyles, field.TypeJSON, value)
	}
	if _u.mutation.DatasetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.DatasetTable,
			Columns: []string{chart.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DatasetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.DatasetTable,
			Columns: []string{chart.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DashboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chart.DashboardsTable,
			Columns: chart.DashboardsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDashboardsIDs(); len(nodes) > 0 && !_u.mutation.DashboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chart.DashboardsTable,
			Columns: chart.DashboardsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DashboardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chart.DashboardsTable,
			Columns: chart.DashboardsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChartUpdateOne is the builder for updating a single Chart entity.
type ChartUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChartMutation
}

// SetTitle sets the "title" field.
func (_u *ChartUpdateOne) SetTitle(v string) *ChartUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableTitle(v *string) *ChartUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ChartUpdateOne) SetConfig(v map[string]interface{}) *ChartUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetColumnStyles sets the "column_styles" field.
func (_u *ChartUpdateOne) SetColumnStyles(v map[string]interface{}) *ChartUpdateOne {
	_u.mutation.SetColumnStyles(v)
	return _u
}

// SetDatasetID sets the "dataset" edge to the Dataset entity by ID.
func (_u *ChartUpdateOne) SetDatasetID(id int) *ChartUpdateOne {
	_u.mutation.SetDatasetID(id)
	return _u
}

// SetNillableDatasetID sets the "dataset" edge to the Dataset entity by ID if the given value is not nil.
func (_u *ChartUpdateOne) SetNillableDatasetID(id *int) *ChartUpdateOne {
	if id != nil {
		_u = _u.SetDatasetID(*id)
	}
	return _u
}

// SetDataset sets the "dataset" edge to the Dataset entity.
func (_u *ChartUpdateOne) SetDataset(v *Dataset) *ChartUpdateOne {
	return _u.SetDatasetID(v.ID)
}

// AddDashboardIDs adds the "dashboards" edge to the Dashboard entity by IDs.
func (_u *ChartUpdateOne) AddDashboardIDs(ids ...int) *ChartUpdateOne {
	_u.mutation.AddDashboardIDs(ids...)
	return _u
}

// AddDashboards adds the "dashboards" edges to the Dashboard entity.
func (_u *ChartUpdateOne) AddDashboards(v ...*Dashboard) *ChartUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDashboardIDs(ids...)
}

// Mutation returns the ChartMutation object of the builder.
func (_u *ChartUpdateOne) Mutation() *ChartMutation {
	return _u.mutation
}

// ClearDataset clears the "dataset" edge to the Dataset entity.
func (_u *ChartUpdateOne) ClearDataset() *ChartUpdateOne {
	_u.mutation.ClearDataset()
	return _u
}

// ClearDashboards clears all "dashboards" edges to the Dashboard entity.
func (_u *ChartUpdateOne) ClearDashboards() *ChartUpdateOne {
	_u.mutation.ClearDashboards()
	return _u
}

// RemoveDashboardIDs removes the "dashboards" edge to Dashboard entities by IDs.
func (_u *ChartUpdateOne) RemoveDashboardIDs(ids ...int) *ChartUpdateOne {
	_u.mutation.RemoveDashboardIDs(ids...)
	return _u
}

// RemoveDashboards removes "dashboards" edges to Dashboard entities.
func (_u *ChartUpdateOne) RemoveDashboards(v ...*Dashboard) *ChartUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDashboardIDs(ids...)
}

// Where appends a list predicates to the ChartUpdate builder.
func (_u *ChartUpdateOne) Where(ps ...predicate.Chart) *ChartUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChartUpdateOne) Select(field string, fields ...string) *ChartUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Chart entity.
func (_u *ChartUpdateOne) Save(ctx context.Context) (*Chart, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChartUpdateOne) SaveX(ctx context.Context) *Chart {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChartUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChartUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ChartUpdateOne) sqlSave(ctx context.Context) (_node *Chart, err error) {
	_spec := sqlgraph.NewUpdateSpec(chart.Table, chart.Columns, sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chart.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chart.FieldID)
		for _, f := range fields {
			if !chart.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chart.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(chart.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(chart.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ColumnStyles(); ok {
		_spec.SetField(chart.FieldColumnStyles, field.TypeJSON, value)
	}
	if _u.mutation.DatasetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.DatasetTable,
			Columns: []string{chart.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DatasetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.DatasetTable,
			Columns: []string{chart.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DashboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chart.DashboardsTable,
			Columns: chart.DashboardsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDashboardsIDs(); len(nodes) > 0 && !_u.mutation.DashboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chart.DashboardsTable,
			Columns: chart.DashboardsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DashboardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chart.DashboardsTable,
			Columns: chart.DashboardsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chart{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
