// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/chart"
	"bi-metadata/ent/dataset"
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Chart is the model entity for the Chart schema.
type Chart struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Config holds the value of the "config" field.
	Config map[string]interface{} `json:"config,omitempty"`
	// ColumnStyles holds the value of the "column_styles" field.
	ColumnStyles map[string]interface{} `json:"column_styles,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChartQuery when eager-loading is set.
	Edges          ChartEdges `json:"edges"`
	dataset_charts *int
	selectValues   sql.SelectValues
}

// ChartEdges holds the relations/edges for other nodes in the graph.
type ChartEdges struct {
	// Dataset holds the value of the dataset edge.
	Dataset *Dataset `json:"dataset,omitempty"`
	// Dashboards holds the value of the dashboards edge.
	Dashboards []*Dashboard `json:"dashboards,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DatasetOrErr returns the Dataset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChartEdges) DatasetOrErr() (*Dataset, error) {
	if e.Dataset != nil {
		return e.Dataset, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: dataset.Label}
	}
	return nil, &NotLoadedError{edge: "dataset"}
}

// DashboardsOrErr returns the Dashboards value or an error if the edge
// was not loaded in eager-loading.
func (e ChartEdges) DashboardsOrErr() ([]*Dashboard, error) {
	if e.loadedTypes[1] {
		return e.Dashboards, nil
	}
	return nil, &NotLoadedError{edge: "dashboards"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Chart) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chart.FieldConfig, chart.FieldColumnStyles:
			values[i] = new([]byte)
		case chart.FieldID:
			values[i] = new(sql.NullInt64)
		case chart.FieldTitle:
			values[i] = new(sql.NullString)
		case chart.ForeignKeys[0]: // dataset_charts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Chart fields.
func (_m *Chart) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chart.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chart.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case chart.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case chart.FieldColumnStyles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field column_styles", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ColumnStyles); err != nil {
					return fmt.Errorf("unmarshal field column_styles: %w", err)
				}
			}
		case chart.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field dataset_charts", value)
			} else if value.Valid {
				_m.dataset_charts = new(int)
				*_m.dataset_charts = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Chart.
// This includes values selected through modifiers, order, etc.
func (_m *Chart) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDataset queries the "dataset" edge of the Chart entity.
func (_m *Chart) QueryDataset() *DatasetQuery {
	return NewChartClient(_m.config).QueryDataset(_m)
}

// QueryDashboards queries the "dashboards" edge of the Chart entity.
func (_m *Chart) QueryDashboards() *DashboardQuery {
	return NewChartClient(_m.config).QueryDashboards(_m)
}

// Update returns a builder for updating this Chart.
// Note that you need to call Chart.Unwrap() before calling this method if this Chart
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Chart) Update() *ChartUpdateOne {
	return NewChartClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Chart entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Chart) Unwrap() *Chart {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Chart is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Chart) String() string {
	var builder strings.Builder
	builder.WriteString("Chart(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteString(", ")
	builder.WriteString("column_styles=")
	builder.WriteString(fmt.Sprintf("%v", _m.ColumnStyles))
	builder.WriteByte(')')
	return builder.String()
}

// Charts is a parsable slice of Chart.
type Charts []*Chart
