// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/chart"
	"bi-metadata/ent/dashboard"
	"bi-metadata/ent/dataset"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChartCreate is the builder for creating a Chart entity.
type ChartCreate struct {
	config
	mutation *ChartMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ChartCreate) SetTitle(v string) *ChartCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *ChartCreate) SetConfig(v map[string]interface{}) *ChartCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetColumnStyles sets the "column_styles" field.
func (_c *ChartCreate) SetColumnStyles(v map[string]interface{}) *ChartCreate {
	_c.mutation.SetColumnStyles(v)
	return _c
}

// SetDatasetID sets the "dataset" edge to the Dataset entity by ID.
func (_c *ChartCreate) SetDatasetID(id int) *ChartCreate {
	_c.mutation.SetDatasetID(id)
	return _c
}

// SetNillableDatasetID sets the "dataset" edge to the Dataset entity by ID if the given value is not nil.
func (_c *ChartCreate) SetNillableDatasetID(id *int) *ChartCreate {
	if id != nil {
		_c = _c.SetDatasetID(*id)
	}
	return _c
}

// SetDataset sets the "dataset" edge to the Dataset entity.
func (_c *ChartCreate) SetDataset(v *Dataset) *ChartCreate {
	return _c.SetDatasetID(v.ID)
}

// AddDashboardIDs adds the "dashboards" edge to the Dashboard entity by IDs.
func (_c *ChartCreate) AddDashboardIDs(ids ...int) *ChartCreate {
	_c.mutation.AddDashboardIDs(ids...)
	return _c
}

// AddDashboards adds the "dashboards" edges to the Dashboard entity.
func (_c *ChartCreate) AddDashboards(v ...*Dashboard) *ChartCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDashboardIDs(ids...)
}

// Mutation returns the ChartMutation object of the builder.
func (_c *ChartCreate) Mutation() *ChartMutation {
	return _c.mutation
}

// Save creates the Chart in the database.
func (_c *ChartCreate) Save(ctx context.Context) (*Chart, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChartCreate) SaveX(ctx context.Context) *Chart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChartCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChartCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChartCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Chart.title"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "Chart.config"`)}
	}
	if _, ok := _c.mutation.ColumnStyles(); !ok {
		return &ValidationError{Name: "column_styles", err: errors.New(`ent: missing required field "Chart.column_styles"`)}
	}
	return nil
}

func (_c *ChartCreate) sqlSave(ctx context.Context) (*Chart, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChartCreate) createSpec() (*Chart, *sqlgraph.CreateSpec) {
	var (
		_node = &Chart{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chart.Table, sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(chart.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(chart.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.ColumnStyles(); ok {
		_spec.SetField(chart.FieldColumnStyles, field.TypeJSON, value)
		_node.ColumnStyles = value
	}
	if nodes := _c.mutation.DatasetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chart.DatasetTable,
			Columns: []string{chart.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.dataset_charts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DashboardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   chart.DashboardsTable,
			Columns: chart.DashboardsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChartCreateBulk is the builder for creating many Chart entities in bulk.
type ChartCreateBulk struct {
	config
	err      error
	builders []*ChartCreate
}

// Save creates the Chart entities in the database.
func (_c *ChartCreateBulk) Save(ctx context.Context) ([]*Chart, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chart, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChartMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChartCreateBulk) SaveX(ctx context.Context) []*Chart {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChartCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChartCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
