// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"bi-metadata/ent/migrate"

	"bi-metadata/ent/chart"
	"bi-metadata/ent/dashboard"
	"bi-metadata/ent/dataset"
	"bi-metadata/ent/rlsrule"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Chart is the client for interacting with the Chart builders.
	Chart *ChartClient
	// Dashboard is the client for interacting with the Dashboard builders.
	Dashboard *DashboardClient
	// Dataset is the client for interacting with the Dataset builders.
	Dataset *DatasetClient
	// RlsRule is the client for interacting with the RlsRule builders.
	RlsRule *RlsRuleClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Chart = NewChartClient(c.config)
	c.Dashboard = NewDashboardClient(c.config)
	c.Dataset = NewDatasetClient(c.config)
	c.RlsRule = NewRlsRuleClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Chart:     NewChartClient(cfg),
		Dashboard: NewDashboardClient(cfg),
		Dataset:   NewDatasetClient(cfg),
		RlsRule:   NewRlsRuleClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Chart:     NewChartClient(cfg),
		Dashboard: NewDashboardClient(cfg),
		Dataset:   NewDatasetClient(cfg),
		RlsRule:   NewRlsRuleClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Chart.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Chart.Use(hooks...)
	c.Dashboard.Use(hooks...)
	c.Dataset.Use(hooks...)
	c.RlsRule.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Chart.Intercept(interceptors...)
	c.Dashboard.Intercept(interceptors...)
	c.Dataset.Intercept(interceptors...)
	c.RlsRule.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ChartMutation:
		return c.Chart.mutate(ctx, m)
	case *DashboardMutation:
		return c.Dashboard.mutate(ctx, m)
	case *DatasetMutation:
		return c.Dataset.mutate(ctx, m)
	case *RlsRuleMutation:
		return c.RlsRule.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ChartClient is a client for the Chart schema.
type ChartClient struct {
	config
}

// NewChartClient returns a client for the Chart from the given config.
func NewChartClient(c config) *ChartClient {
	return &ChartClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `chart.Hooks(f(g(h())))`.
func (c *ChartClient) Use(hooks ...Hook) {
	c.hooks.Chart = append(c.hooks.Chart, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `chart.Intercept(f(g(h())))`.
func (c *ChartClient) Intercept(interceptors ...Interceptor) {
	c.inters.Chart = append(c.inters.Chart, interceptors...)
}

// Create returns a builder for creating a Chart entity.
func (c *ChartClient) Create() *ChartCreate {
	mutation := newChartMutation(c.config, OpCreate)
	return &ChartCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Chart entities.
func (c *ChartClient) CreateBulk(builders ...*ChartCreate) *ChartCreateBulk {
	return &ChartCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChartClient) MapCreateBulk(slice any, setFunc func(*ChartCreate, int)) *ChartCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChartCreateBulk{err: fmt.Errorf("calling to ChartClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChartCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChartCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Chart.
func (c *ChartClient) Update() *ChartUpdate {
	mutation := newChartMutation(c.config, OpUpdate)
	return &ChartUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChartClient) UpdateOne(_m *Chart) *ChartUpdateOne {
	mutation := newChartMutation(c.config, OpUpdateOne, withChart(_m))
	return &ChartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChartClient) UpdateOneID(id int) *ChartUpdateOne {
	mutation := newChartMutation(c.config, OpUpdateOne, withChartID(id))
	return &ChartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Chart.
func (c *ChartClient) Delete() *ChartDelete {
	mutation := newChartMutation(c.config, OpDelete)
	return &ChartDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChartClient) DeleteOne(_m *Chart) *ChartDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChartClient) DeleteOneID(id int) *ChartDeleteOne {
	builder := c.Delete().Where(chart.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChartDeleteOne{builder}
}

// Query returns a query builder for Chart.
func (c *ChartClient) Query() *ChartQuery {
	return &ChartQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChart},
		inters: c.Interceptors(),
	}
}

// Get returns a Chart entity by its id.
func (c *ChartClient) Get(ctx context.Context, id int) (*Chart, error) {
	return c.Query().Where(chart.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChartClient) GetX(ctx context.Context, id int) *Chart {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDataset queries the dataset edge of a Chart.
func (c *ChartClient) QueryDataset(_m *Chart) *DatasetQuery {
	query := (&DatasetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(chart.Table, chart.FieldID, id),
			sqlgraph.To(dataset.Table, dataset.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chart.DatasetTable, chart.DatasetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDashboards queries the dashboards edge of a Chart.
func (c *ChartClient) QueryDashboards(_m *Chart) *DashboardQuery {
	query := (&DashboardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(chart.Table, chart.FieldID, id),
			sqlgraph.To(dashboard.Table, dashboard.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, chart.DashboardsTable, chart.DashboardsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChartClient) Hooks() []Hook {
	return c.hooks.Chart
}

// Interceptors returns the client interceptors.
func (c *ChartClient) Interceptors() []Interceptor {
	return c.inters.Chart
}

func (c *ChartClient) mutate(ctx context.Context, m *ChartMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChartCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChartUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChartDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Chart mutation op: %q", m.Op())
	}
}

// DashboardClient is a client for the Dashboard schema.
type DashboardClient struct {
	config
}

// NewDashboardClient returns a client for the Dashboard from the given config.
func NewDashboardClient(c config) *DashboardClient {
	return &DashboardClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dashboard.Hooks(f(g(h())))`.
func (c *DashboardClient) Use(hooks ...Hook) {
	c.hooks.Dashboard = append(c.hooks.Dashboard, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dashboard.Intercept(f(g(h())))`.
func (c *DashboardClient) Intercept(interceptors ...Interceptor) {
	c.inters.Dashboard = append(c.inters.Dashboard, interceptors...)
}

// Create returns a builder for creating a Dashboard entity.
func (c *DashboardClient) Create() *DashboardCreate {
	mutation := newDashboardMutation(c.config, OpCreate)
	return &DashboardCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Dashboard entities.
func (c *DashboardClient) CreateBulk(builders ...*DashboardCreate) *DashboardCreateBulk {
	return &DashboardCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DashboardClient) MapCreateBulk(slice any, setFunc func(*DashboardCreate, int)) *DashboardCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DashboardCreateBulk{err: fmt.Errorf("calling to DashboardClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DashboardCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DashboardCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Dashboard.
func (c *DashboardClient) Update() *DashboardUpdate {
	mutation := newDashboardMutation(c.config, OpUpdate)
	return &DashboardUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DashboardClient) UpdateOne(_m *Dashboard) *DashboardUpdateOne {
	mutation := newDashboardMutation(c.config, OpUpdateOne, withDashboard(_m))
	return &DashboardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DashboardClient) UpdateOneID(id int) *DashboardUpdateOne {
	mutation := newDashboardMutation(c.config, OpUpdateOne, withDashboardID(id))
	return &DashboardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Dashboard.
func (c *DashboardClient) Delete() *DashboardDelete {
	mutation := newDashboardMutation(c.config, OpDelete)
	return &DashboardDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DashboardClient) DeleteOne(_m *Dashboard) *DashboardDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DashboardClient) DeleteOneID(id int) *DashboardDeleteOne {
	builder := c.Delete().Where(dashboard.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DashboardDeleteOne{builder}
}

// Query returns a query builder for Dashboard.
func (c *DashboardClient) Query() *DashboardQuery {
	return &DashboardQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDashboard},
		inters: c.Interceptors(),
	}
}

// Get returns a Dashboard entity by its id.
func (c *DashboardClient) Get(ctx context.Context, id int) (*Dashboard, error) {
	return c.Query().Where(dashboard.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DashboardClient) GetX(ctx context.Context, id int) *Dashboard {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCharts queries the charts edge of a Dashboard.
func (c *DashboardClient) QueryCharts(_m *Dashboard) *ChartQuery {
	query := (&ChartClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dashboard.Table, dashboard.FieldID, id),
			sqlgraph.To(chart.Table, chart.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, dashboard.ChartsTable, dashboard.ChartsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DashboardClient) Hooks() []Hook {
	return c.hooks.Dashboard
}

// Interceptors returns the client interceptors.
func (c *DashboardClient) Interceptors() []Interceptor {
	return c.inters.Dashboard
}

func (c *DashboardClient) mutate(ctx context.Context, m *DashboardMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DashboardCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DashboardUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DashboardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DashboardDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Dashboard mutation op: %q", m.Op())
	}
}

// DatasetClient is a client for the Dataset schema.
type DatasetClient struct {
	config
}

// NewDatasetClient returns a client for the Dataset from the given config.
func NewDatasetClient(c config) *DatasetClient {
	return &DatasetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dataset.Hooks(f(g(h())))`.
func (c *DatasetClient) Use(hooks ...Hook) {
	c.hooks.Dataset = append(c.hooks.Dataset, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dataset.Intercept(f(g(h())))`.
func (c *DatasetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Dataset = append(c.inters.Dataset, interceptors...)
}

// Create returns a builder for creating a Dataset entity.
func (c *DatasetClient) Create() *DatasetCreate {
	mutation := newDatasetMutation(c.config, OpCreate)
	return &DatasetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Dataset entities.
func (c *DatasetClient) CreateBulk(builders ...*DatasetCreate) *DatasetCreateBulk {
	return &DatasetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DatasetClient) MapCreateBulk(slice any, setFunc func(*DatasetCreate, int)) *DatasetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DatasetCreateBulk{err: fmt.Errorf("calling to DatasetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DatasetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DatasetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Dataset.
func (c *DatasetClient) Update() *DatasetUpdate {
	mutation := newDatasetMutation(c.config, OpUpdate)
	return &DatasetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DatasetClient) UpdateOne(_m *Dataset) *DatasetUpdateOne {
	mutation := newDatasetMutation(c.config, OpUpdateOne, withDataset(_m))
	return &DatasetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DatasetClient) UpdateOneID(id int) *DatasetUpdateOne {
	mutation := newDatasetMutation(c.config, OpUpdateOne, withDatasetID(id))
	return &DatasetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Dataset.
func (c *DatasetClient) Delete() *DatasetDelete {
	mutation := newDatasetMutation(c.config, OpDelete)
	return &DatasetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DatasetClient) DeleteOne(_m *Dataset) *DatasetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DatasetClient) DeleteOneID(id int) *DatasetDeleteOne {
	builder := c.Delete().Where(dataset.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DatasetDeleteOne{builder}
}

// Query returns a query builder for Dataset.
func (c *DatasetClient) Query() *DatasetQuery {
	return &DatasetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDataset},
		inters: c.Interceptors(),
	}
}

// Get returns a Dataset entity by its id.
func (c *DatasetClient) Get(ctx context.Context, id int) (*Dataset, error) {
	return c.Query().Where(dataset.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DatasetClient) GetX(ctx context.Context, id int) *Dataset {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCharts queries the charts edge of a Dataset.
func (c *DatasetClient) QueryCharts(_m *Dataset) *ChartQuery {
	query := (&ChartClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dataset.Table, dataset.FieldID, id),
			sqlgraph.To(chart.Table, chart.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dataset.ChartsTable, dataset.ChartsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRlsRules queries the rls_rules edge of a Dataset.
func (c *DatasetClient) QueryRlsRules(_m *Dataset) *RlsRuleQuery {
	query := (&RlsRuleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dataset.Table, dataset.FieldID, id),
			sqlgraph.To(rlsrule.Table, rlsrule.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dataset.RlsRulesTable, dataset.RlsRulesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DatasetClient) Hooks() []Hook {
	return c.hooks.Dataset
}

// Interceptors returns the client interceptors.
func (c *DatasetClient) Interceptors() []Interceptor {
	return c.inters.Dataset
}

func (c *DatasetClient) mutate(ctx context.Context, m *DatasetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DatasetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DatasetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DatasetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DatasetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Dataset mutation op: %q", m.Op())
	}
}

// RlsRuleClient is a client for the RlsRule schema.
type RlsRuleClient struct {
	config
}

// NewRlsRuleClient returns a client for the RlsRule from the given config.
func NewRlsRuleClient(c config) *RlsRuleClient {
	return &RlsRuleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `rlsrule.Hooks(f(g(h())))`.
func (c *RlsRuleClient) Use(hooks ...Hook) {
	c.hooks.RlsRule = append(c.hooks.RlsRule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `rlsrule.Intercept(f(g(h())))`.
func (c *RlsRuleClient) Intercept(interceptors ...Interceptor) {
	c.inters.RlsRule = append(c.inters.RlsRule, interceptors...)
}

// Create returns a builder for creating a RlsRule entity.
func (c *RlsRuleClient) Create() *RlsRuleCreate {
	mutation := newRlsRuleMutation(c.config, OpCreate)
	return &RlsRuleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RlsRule entities.
func (c *RlsRuleClient) CreateBulk(builders ...*RlsRuleCreate) *RlsRuleCreateBulk {
	return &RlsRuleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RlsRuleClient) MapCreateBulk(slice any, setFunc func(*RlsRuleCreate, int)) *RlsRuleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RlsRuleCreateBulk{err: fmt.Errorf("calling to RlsRuleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RlsRuleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RlsRuleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RlsRule.
func (c *RlsRuleClient) Update() *RlsRuleUpdate {
	mutation := newRlsRuleMutation(c.config, OpUpdate)
	return &RlsRuleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RlsRuleClient) UpdateOne(_m *RlsRule) *RlsRuleUpdateOne {
	mutation := newRlsRuleMutation(c.config, OpUpdateOne, withRlsRule(_m))
	return &RlsRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RlsRuleClient) UpdateOneID(id int) *RlsRuleUpdateOne {
	mutation := newRlsRuleMutation(c.config, OpUpdateOne, withRlsRuleID(id))
	return &RlsRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RlsRule.
func (c *RlsRuleClient) Delete() *RlsRuleDelete {
	mutation := newRlsRuleMutation(c.config, OpDelete)
	return &RlsRuleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RlsRuleClient) DeleteOne(_m *RlsRule) *RlsRuleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RlsRuleClient) DeleteOneID(id int) *RlsRuleDeleteOne {
	builder := c.Delete().Where(rlsrule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RlsRuleDeleteOne{builder}
}

// Query returns a query builder for RlsRule.
func (c *RlsRuleClient) Query() *RlsRuleQuery {
	return &RlsRuleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRlsRule},
		inters: c.Interceptors(),
	}
}

// Get returns a RlsRule entity by its id.
func (c *RlsRuleClient) Get(ctx context.Context, id int) (*RlsRule, error) {
	return c.Query().Where(rlsrule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RlsRuleClient) GetX(ctx context.Context, id int) *RlsRule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDataset queries the dataset edge of a RlsRule.
func (c *RlsRuleClient) QueryDataset(_m *RlsRule) *DatasetQuery {
	query := (&DatasetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(rlsrule.Table, rlsrule.FieldID, id),
			sqlgraph.To(dataset.Table, dataset.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, rlsrule.DatasetTable, rlsrule.DatasetColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RlsRuleClient) Hooks() []Hook {
	return c.hooks.RlsRule
}

// Interceptors returns the client interceptors.
func (c *RlsRuleClient) Interceptors() []Interceptor {
	return c.inters.RlsRule
}

func (c *RlsRuleClient) mutate(ctx context.Context, m *RlsRuleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RlsRuleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RlsRuleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RlsRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RlsRuleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RlsRule mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Chart, Dashboard, Dataset, RlsRule []ent.Hook
	}
	inters struct {
		Chart, Dashboard, Dataset, RlsRule []ent.Interceptor
	}
)
