// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/chart"
	"bi-metadata/ent/dashboard"
	"bi-metadata/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DashboardUpdate is the builder for updating Dashboard entities.
type DashboardUpdate struct {
	config
	hooks    []Hook
	mutation *DashboardMutation
}

// Where appends a list predicates to the DashboardUpdate builder.
func (_u *DashboardUpdate) Where(ps ...predicate.Dashboard) *DashboardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DashboardUpdate) SetName(v string) *DashboardUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DashboardUpdate) SetNillableName(v *string) *DashboardUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLayout sets the "layout" field.
func (_u *DashboardUpdate) SetLayout(v map[string]interface{}) *DashboardUpdate {
	_u.mutation.SetLayout(v)
	return _u
}

// AddChartIDs adds the "charts" edge to the Chart entity by IDs.
func (_u *DashboardUpdate) AddChartIDs(ids ...int) *DashboardUpdate {
	_u.mutation.AddChartIDs(ids...)
	return _u
}

// AddCharts adds the "charts" edges to the Chart entity.
func (_u *DashboardUpdate) AddCharts(v ...*Chart) *DashboardUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChartIDs(ids...)
}

// Mutation returns the DashboardMutation object of the builder.
func (_u *DashboardUpdate) Mutation() *DashboardMutation {
	return _u.mutation
}

// ClearCharts clears all "charts" edges to the Chart entity.
func (_u *DashboardUpdate) ClearCharts() *DashboardUpdate {
	_u.mutation.ClearCharts()
	return _u
}

// RemoveChartIDs removes the "charts" edge to Chart entities by IDs.
func (_u *DashboardUpdate) RemoveChartIDs(ids ...int) *DashboardUpdate {
	_u.mutation.RemoveChartIDs(ids...)
	return _u
}

// RemoveCharts removes "charts" edges to Chart entities.
func (_u *DashboardUpdate) RemoveCharts(v ...*Chart) *DashboardUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChartIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DashboardUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DashboardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DashboardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DashboardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DashboardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dashboard.Table, dashboard.Columns, sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dashboard.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Layout(); ok {
		_spec.SetField(dashboard.FieldLayout, field.TypeJSON, value)
	}
	if _u.mutation.ChartsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dashboard.ChartsTable,
			Columns: dashboard.ChartsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChartsIDs(); len(nodes) > 0 && !_u.mutation.ChartsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dashboard.ChartsTable,
			Columns: dashboard.ChartsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChartsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dashboard.ChartsTable,
			Columns: dashboard.ChartsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dashboard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DashboardUpdateOne is the builder for updating a single Dashboard entity.
type DashboardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DashboardMutation
}

// SetName sets the "name" field.
func (_u *DashboardUpdateOne) SetName(v string) *DashboardUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DashboardUpdateOne) SetNillableName(v *string) *DashboardUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLayout sets the "layout" field.
func (_u *DashboardUpdateOne) SetLayout(v map[string]interface{}) *DashboardUpdateOne {
	_u.mutation.SetLayout(v)
	return _u
}

// AddChartIDs adds the "charts" edge to the Chart entity by IDs.
func (_u *DashboardUpdateOne) AddChartIDs(ids ...int) *DashboardUpdateOne {
	_u.mutation.AddChartIDs(ids...)
	return _u
}

// AddCharts adds the "charts" edges to the Chart entity.
func (_u *DashboardUpdateOne) AddCharts(v ...*Chart) *DashboardUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChartIDs(ids...)
}

// Mutation returns the DashboardMutation object of the builder.
func (_u *DashboardUpdateOne) Mutation() *DashboardMutation {
	return _u.mutation
}

// ClearCharts clears all "charts" edges to the Chart entity.
func (_u *DashboardUpdateOne) ClearCharts() *DashboardUpdateOne {
	_u.mutation.ClearCharts()
	return _u
}

// RemoveChartIDs removes the "charts" edge to Chart entities by IDs.
func (_u *DashboardUpdateOne) RemoveChartIDs(ids ...int) *DashboardUpdateOne {
	_u.mutation.RemoveChartIDs(ids...)
	return _u
}

// RemoveCharts removes "charts" edges to Chart entities.
func (_u *DashboardUpdateOne) RemoveCharts(v ...*Chart) *DashboardUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChartIDs(ids...)
}

// Where appends a list predicates to the DashboardUpdate builder.
func (_u *DashboardUpdateOne) Where(ps ...predicate.Dashboard) *DashboardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DashboardUpdateOne) Select(field string, fields ...string) *DashboardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Dashboard entity.
func (_u *DashboardUpdateOne) Save(ctx context.Context) (*Dashboard, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DashboardUpdateOne) SaveX(ctx context.Context) *Dashboard {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DashboardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DashboardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DashboardUpdateOne) sqlSave(ctx context.Context) (_node *Dashboard, err error) {
	_spec := sqlgraph.NewUpdateSpec(dashboard.Table, dashboard.Columns, sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dashboard.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dashboard.FieldID)
		for _, f := range fields {
			if !dashboard.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dashboard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dashboard.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Layout(); ok {
		_spec.SetField(dashboard.FieldLayout, field.TypeJSON, value)
	}
	if _u.mutation.ChartsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dashboard.ChartsTable,
			Columns: dashboard.ChartsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChartsIDs(); len(nodes) > 0 && !_u.mutation.ChartsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dashboard.ChartsTable,
			Columns: dashboard.ChartsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChartsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dashboard.ChartsTable,
			Columns: dashboard.ChartsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Dashboard{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dashboard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
