// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/chart"
	"bi-metadata/ent/dashboard"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DashboardCreate is the builder for creating a Dashboard entity.
type DashboardCreate struct {
	config
	mutation *DashboardMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *DashboardCreate) SetName(v string) *DashboardCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLayout sets the "layout" field.
func (_c *DashboardCreate) SetLayout(v map[string]interface{}) *DashboardCreate {
	_c.mutation.SetLayout(v)
	return _c
}

// AddChartIDs adds the "charts" edge to the Chart entity by IDs.
func (_c *DashboardCreate) AddChartIDs(ids ...int) *DashboardCreate {
	_c.mutation.AddChartIDs(ids...)
	return _c
}

// AddCharts adds the "charts" edges to the Chart entity.
func (_c *DashboardCreate) AddCharts(v ...*Chart) *DashboardCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChartIDs(ids...)
}

// Mutation returns the DashboardMutation object of the builder.
func (_c *DashboardCreate) Mutation() *DashboardMutation {
	return _c.mutation
}

// Save creates the Dashboard in the database.
func (_c *DashboardCreate) Save(ctx context.Context) (*Dashboard, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DashboardCreate) SaveX(ctx context.Context) *Dashboard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DashboardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DashboardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DashboardCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Dashboard.name"`)}
	}
	if _, ok := _c.mutation.Layout(); !ok {
		return &ValidationError{Name: "layout", err: errors.New(`ent: missing required field "Dashboard.layout"`)}
	}
	return nil
}

func (_c *DashboardCreate) sqlSave(ctx context.Context) (*Dashboard, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DashboardCreate) createSpec() (*Dashboard, *sqlgraph.CreateSpec) {
	var (
		_node = &Dashboard{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dashboard.Table, sqlgraph.NewFieldSpec(dashboard.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dashboard.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Layout(); ok {
		_spec.SetField(dashboard.FieldLayout, field.TypeJSON, value)
		_node.Layout = value
	}
	if nodes := _c.mutation.ChartsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   dashboard.ChartsTable,
			Columns: dashboard.ChartsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chart.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DashboardCreateBulk is the builder for creating many Dashboard entities in bulk.
type DashboardCreateBulk struct {
	config
	err      error
	builders []*DashboardCreate
}

// Save creates the Dashboard entities in the database.
func (_c *DashboardCreateBulk) Save(ctx context.Context) ([]*Dashboard, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Dashboard, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DashboardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DashboardCreateBulk) SaveX(ctx context.Context) []*Dashboard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DashboardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DashboardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
