// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/chart"
	"bi-metadata/ent/dashboard"
	"bi-metadata/ent/dataset"
	"bi-metadata/ent/predicate"
	"bi-metadata/ent/rlsrule"
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeChart     = "Chart"
	TypeDashboard = "Dashboard"
	TypeDataset   = "Dataset"
	TypeRlsRule   = "RlsRule"
)

// ChartMutation represents an operation that mutates the Chart nodes in the graph.
type ChartMutation struct {
	config
	op                Op
	typ               string
	id                *int
	title             *string
	_config           *map[string]interface{}
	column_styles     *map[string]interface{}
	clearedFields     map[string]struct{}
	dataset           *int
	cleareddataset    bool
	dashboards        map[int]struct{}
	removeddashboards map[int]struct{}
	cleareddashboards bool
	done              bool
	oldValue          func(context.Context) (*Chart, error)
	predicates        []predicate.Chart
}

var _ ent.Mutation = (*ChartMutation)(nil)

// chartOption allows management of the mutation configuration using functional options.
type chartOption func(*ChartMutation)

// newChartMutation creates new mutation for the Chart entity.
func newChartMutation(c config, op Op, opts ...chartOption) *ChartMutation {
	m := &ChartMutation{
		config:        c,
		op:            op,
		typ:           TypeChart,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withChartID sets the ID field of the mutation.
func withChartID(id int) chartOption {
	return func(m *ChartMutation) {
		var (
			err   error
			once  sync.Once
			value *Chart
		)
		m.oldValue = func(ctx context.Context) (*Chart, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Chart.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withChart sets the old Chart of the mutation.
func withChart(node *Chart) chartOption {
	return func(m *ChartMutation) {
		m.oldValue = func(context.Context) (*Chart, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ChartMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ChartMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ChartMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ChartMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Chart.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTitle sets the "title" field.
func (m *ChartMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *ChartMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Chart entity.
// If the Chart object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ChartMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *ChartMutation) ResetTitle() {
	m.title = nil
}

// SetConfig sets the "config" field.
func (m *ChartMutation) SetConfig(value map[string]interface{}) {
	m._config = &value
}

// Config returns the value of the "config" field in the mutation.
func (m *ChartMutation) Config() (r map[string]interface{}, exists bool) {
	v := m._config
	if v == nil {
		return
	}
	return *v, true
}

// OldConfig returns the old "config" field's value of the Chart entity.
// If the Chart object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ChartMutation) OldConfig(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldConfig is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldConfig requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldConfig: %w", err)
	}
	return oldValue.Config, nil
}

// ResetConfig resets all changes to the "config" field.
func (m *ChartMutation) ResetConfig() {
	m._config = nil
}

// SetColumnStyles sets the "column_styles" field.
func (m *ChartMutation) SetColumnStyles(value map[string]interface{}) {
	m.column_styles = &value
}

// ColumnStyles returns the value of the "column_styles" field in the mutation.
func (m *ChartMutation) ColumnStyles() (r map[string]interface{}, exists bool) {
	v := m.column_styles
	if v == nil {
		return
	}
	return *v, true
}

// OldColumnStyles returns the old "column_styles" field's value of the Chart entity.
// If the Chart object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ChartMutation) OldColumnStyles(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldColumnStyles is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldColumnStyles requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldColumnStyles: %w", err)
	}
	return oldValue.ColumnStyles, nil
}

// ResetColumnStyles resets all changes to the "column_styles" field.
func (m *ChartMutation) ResetColumnStyles() {
	m.column_styles = nil
}

// SetDatasetID sets the "dataset" edge to the Dataset entity by id.
func (m *ChartMutation) SetDatasetID(id int) {
	m.dataset = &id
}

// ClearDataset clears the "dataset" edge to the Dataset entity.
func (m *ChartMutation) ClearDataset() {
	m.cleareddataset = true
}

// DatasetCleared reports if the "dataset" edge to the Dataset entity was cleared.
func (m *ChartMutation) DatasetCleared() bool {
	return m.cleareddataset
}

// DatasetID returns the "dataset" edge ID in the mutation.
func (m *ChartMutation) DatasetID() (id int, exists bool) {
	if m.dataset != nil {
		return *m.dataset, true
	}
	return
}

// DatasetIDs returns the "dataset" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// DatasetID instead. It exists only for internal usage by the builders.
func (m *ChartMutation) DatasetIDs() (ids []int) {
	if id := m.dataset; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetDataset resets all changes to the "dataset" edge.
func (m *ChartMutation) ResetDataset() {
	m.dataset = nil
	m.cleareddataset = false
}

// AddDashboardIDs adds the "dashboards" edge to the Dashboard entity by ids.
func (m *ChartMutation) AddDashboardIDs(ids ...int) {
	if m.dashboards == nil {
		m.dashboards = make(map[int]struct{})
	}
	for i := range ids {
		m.dashboards[ids[i]] = struct{}{}
	}
}

// ClearDashboards clears the "dashboards" edge to the Dashboard entity.
func (m *ChartMutation) ClearDashboards() {
	m.cleareddashboards = true
}

// DashboardsCleared reports if the "dashboards" edge to the Dashboard entity was cleared.
func (m *ChartMutation) DashboardsCleared() bool {
	return m.cleareddashboards
}

// RemoveDashboardIDs removes the "dashboards" edge to the Dashboard entity by IDs.
func (m *ChartMutation) RemoveDashboardIDs(ids ...int) {
	if m.removeddashboards == nil {
		m.removeddashboards = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.dashboards, ids[i])
		m.removeddashboards[ids[i]] = struct{}{}
	}
}

// RemovedDashboards returns the removed IDs of the "dashboards" edge to the Dashboard entity.
func (m *ChartMutation) RemovedDashboardsIDs() (ids []int) {
	for id := range m.removeddashboards {
		ids = append(ids, id)
	}
	return
}

// DashboardsIDs returns the "dashboards" edge IDs in the mutation.
func (m *ChartMutation) DashboardsIDs() (ids []int) {
	for id := range m.dashboards {
		ids = append(ids, id)
	}
	return
}

// ResetDashboards resets all changes to the "dashboards" edge.
func (m *ChartMutation) ResetDashboards() {
	m.dashboards = nil
	m.cleareddashboards = false
	m.removeddashboards = nil
}

// Where appends a list predicates to the ChartMutation builder.
func (m *ChartMutation) Where(ps ...predicate.Chart) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ChartMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ChartMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Chart, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ChartMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ChartMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Chart).
func (m *ChartMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ChartMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.title != nil {
		fields = append(fields, chart.FieldTitle)
	}
	if m._config != nil {
		fields = append(fields, chart.FieldConfig)
	}
	if m.column_styles != nil {
		fields = append(fields, chart.FieldColumnStyles)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ChartMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case chart.FieldTitle:
		return m.Title()
	case chart.FieldConfig:
		return m.Config()
	case chart.FieldColumnStyles:
		return m.ColumnStyles()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ChartMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case chart.FieldTitle:
		return m.OldTitle(ctx)
	case chart.FieldConfig:
		return m.OldConfig(ctx)
	case chart.FieldColumnStyles:
		return m.OldColumnStyles(ctx)
	}
	return nil, fmt.Errorf("unknown Chart field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ChartMutation) SetField(name string, value ent.Value) error {
	switch name {
	case chart.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case chart.FieldConfig:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetConfig(v)
		return nil
	case chart.FieldColumnStyles:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetColumnStyles(v)
		return nil
	}
	return fmt.Errorf("unknown Chart field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ChartMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ChartMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ChartMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Chart numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ChartMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ChartMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ChartMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Chart nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ChartMutation) ResetField(name string) error {
	switch name {
	case chart.FieldTitle:
		m.ResetTitle()
		return nil
	case chart.FieldConfig:
		m.ResetConfig()
		return nil
	case chart.FieldColumnStyles:
		m.ResetColumnStyles()
		return nil
	}
	return fmt.Errorf("unknown Chart field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ChartMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.dataset != nil {
		edges = append(edges, chart.EdgeDataset)
	}
	if m.dashboards != nil {
		edges = append(edges, chart.EdgeDashboards)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ChartMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case chart.EdgeDataset:
		if id := m.dataset; id != nil {
			return []ent.Value{*id}
		}
	case chart.EdgeDashboards:
		ids := make([]ent.Value, 0, len(m.dashboards))
		for id := range m.dashboards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ChartMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removeddashboards != nil {
		edges = append(edges, chart.EdgeDashboards)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ChartMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case chart.EdgeDashboards:
		ids := make([]ent.Value, 0, len(m.removeddashboards))
		for id := range m.removeddashboards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ChartMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.cleareddataset {
		edges = append(edges, chart.EdgeDataset)
	}
	if m.cleareddashboards {
		edges = append(edges, chart.EdgeDashboards)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ChartMutation) EdgeCleared(name string) bool {
	switch name {
	case chart.EdgeDataset:
		return m.cleareddataset
	case chart.EdgeDashboards:
		return m.cleareddashboards
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ChartMutation) ClearEdge(name string) error {
	switch name {
	case chart.EdgeDataset:
		m.ClearDataset()
		return nil
	}
	return fmt.Errorf("unknown Chart unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ChartMutation) ResetEdge(name string) error {
	switch name {
	case chart.EdgeDataset:
		m.ResetDataset()
		return nil
	case chart.EdgeDashboards:
		m.ResetDashboards()
		return nil
	}
	return fmt.Errorf("unknown Chart edge %s", name)
}

// DashboardMutation represents an operation that mutates the Dashboard nodes in the graph.
type DashboardMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	layout        *map[string]interface{}
	clearedFields map[string]struct{}
	charts        map[int]struct{}
	removedcharts map[int]struct{}
	clearedcharts bool
	done          bool
	oldValue      func(context.Context) (*Dashboard, error)
	predicates    []predicate.Dashboard
}

var _ ent.Mutation = (*DashboardMutation)(nil)

// dashboardOption allows management of the mutation configuration using functional options.
type dashboardOption func(*DashboardMutation)

// newDashboardMutation creates new mutation for the Dashboard entity.
func newDashboardMutation(c config, op Op, opts ...dashboardOption) *DashboardMutation {
	m := &DashboardMutation{
		config:        c,
		op:            op,
		typ:           TypeDashboard,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDashboardID sets the ID field of the mutation.
func withDashboardID(id int) dashboardOption {
	return func(m *DashboardMutation) {
		var (
			err   error
			once  sync.Once
			value *Dashboard
		)
		m.oldValue = func(ctx context.Context) (*Dashboard, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Dashboard.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDashboard sets the old Dashboard of the mutation.
func withDashboard(node *Dashboard) dashboardOption {
	return func(m *DashboardMutation) {
		m.oldValue = func(context.Context) (*Dashboard, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DashboardMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DashboardMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DashboardMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DashboardMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Dashboard.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *DashboardMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *DashboardMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Dashboard entity.
// If the Dashboard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DashboardMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *DashboardMutation) ResetName() {
	m.name = nil
}

// SetLayout sets the "layout" field.
func (m *DashboardMutation) SetLayout(value map[string]interface{}) {
	m.layout = &value
}

// Layout returns the value of the "layout" field in the mutation.
func (m *DashboardMutation) Layout() (r map[string]interface{}, exists bool) {
	v := m.layout
	if v == nil {
		return
	}
	return *v, true
}

// OldLayout returns the old "layout" field's value of the Dashboard entity.
// If the Dashboard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DashboardMutation) OldLayout(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLayout is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLayout requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLayout: %w", err)
	}
	return oldValue.Layout, nil
}

// ResetLayout resets all changes to the "layout" field.
func (m *DashboardMutation) ResetLayout() {
	m.layout = nil
}

// AddChartIDs adds the "charts" edge to the Chart entity by ids.
func (m *DashboardMutation) AddChartIDs(ids ...int) {
	if m.charts == nil {
		m.charts = make(map[int]struct{})
	}
	for i := range ids {
		m.charts[ids[i]] = struct{}{}
	}
}

// ClearCharts clears the "charts" edge to the Chart entity.
func (m *DashboardMutation) ClearCharts() {
	m.clearedcharts = true
}

// ChartsCleared reports if the "charts" edge to the Chart entity was cleared.
func (m *DashboardMutation) ChartsCleared() bool {
	return m.clearedcharts
}

// RemoveChartIDs removes the "charts" edge to the Chart entity by IDs.
func (m *DashboardMutation) RemoveChartIDs(ids ...int) {
	if m.removedcharts == nil {
		m.removedcharts = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.charts, ids[i])
		m.removedcharts[ids[i]] = struct{}{}
	}
}

// RemovedCharts returns the removed IDs of the "charts" edge to the Chart entity.
func (m *DashboardMutation) RemovedChartsIDs() (ids []int) {
	for id := range m.removedcharts {
		ids = append(ids, id)
	}
	return
}

// ChartsIDs returns the "charts" edge IDs in the mutation.
func (m *DashboardMutation) ChartsIDs() (ids []int) {
	for id := range m.charts {
		ids = append(ids, id)
	}
	return
}

// ResetCharts resets all changes to the "charts" edge.
func (m *DashboardMutation) ResetCharts() {
	m.charts = nil
	m.clearedcharts = false
	m.removedcharts = nil
}

// Where appends a list predicates to the DashboardMutation builder.
func (m *DashboardMutation) Where(ps ...predicate.Dashboard) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DashboardMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DashboardMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Dashboard, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DashboardMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DashboardMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Dashboard).
func (m *DashboardMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DashboardMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.name != nil {
		fields = append(fields, dashboard.FieldName)
	}
	if m.layout != nil {
		fields = append(fields, dashboard.FieldLayout)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DashboardMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dashboard.FieldName:
		return m.Name()
	case dashboard.FieldLayout:
		return m.Layout()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DashboardMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dashboard.FieldName:
		return m.OldName(ctx)
	case dashboard.FieldLayout:
		return m.OldLayout(ctx)
	}
	return nil, fmt.Errorf("unknown Dashboard field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DashboardMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dashboard.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case dashboard.FieldLayout:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLayout(v)
		return nil
	}
	return fmt.Errorf("unknown Dashboard field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DashboardMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DashboardMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DashboardMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Dashboard numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DashboardMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DashboardMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DashboardMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Dashboard nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DashboardMutation) ResetField(name string) error {
	switch name {
	case dashboard.FieldName:
		m.ResetName()
		return nil
	case dashboard.FieldLayout:
		m.ResetLayout()
		return nil
	}
	return fmt.Errorf("unknown Dashboard field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DashboardMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.charts != nil {
		edges = append(edges, dashboard.EdgeCharts)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DashboardMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case dashboard.EdgeCharts:
		ids := make([]ent.Value, 0, len(m.charts))
		for id := range m.charts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DashboardMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedcharts != nil {
		edges = append(edges, dashboard.EdgeCharts)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DashboardMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case dashboard.EdgeCharts:
		ids := make([]ent.Value, 0, len(m.removedcharts))
		for id := range m.removedcharts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DashboardMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedcharts {
		edges = append(edges, dashboard.EdgeCharts)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DashboardMutation) EdgeCleared(name string) bool {
	switch name {
	case dashboard.EdgeCharts:
		return m.clearedcharts
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DashboardMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Dashboard unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DashboardMutation) ResetEdge(name string) error {
	switch name {
	case dashboard.EdgeCharts:
		m.ResetCharts()
		return nil
	}
	return fmt.Errorf("unknown Dashboard edge %s", name)
}

// DatasetMutation represents an operation that mutates the Dataset nodes in the graph.
type DatasetMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	name               *string
	source_type        *dataset.SourceType
	connection_details *string
	clearedFields      map[string]struct{}
	charts             map[int]struct{}
	removedcharts      map[int]struct{}
	clearedcharts      bool
	rls_rules          map[int]struct{}
	removedrls_rules   map[int]struct{}
	clearedrls_rules   bool
	done               bool
	oldValue           func(context.Context) (*Dataset, error)
	predicates         []predicate.Dataset
}

var _ ent.Mutation = (*DatasetMutation)(nil)

// datasetOption allows management of the mutation configuration using functional options.
type datasetOption func(*DatasetMutation)

// newDatasetMutation creates new mutation for the Dataset entity.
func newDatasetMutation(c config, op Op, opts ...datasetOption) *DatasetMutation {
	m := &DatasetMutation{
		config:        c,
		op:            op,
		typ:           TypeDataset,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDatasetID sets the ID field of the mutation.
func withDatasetID(id int) datasetOption {
	return func(m *DatasetMutation) {
		var (
			err   error
			once  sync.Once
			value *Dataset
		)
		m.oldValue = func(ctx context.Context) (*Dataset, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Dataset.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDataset sets the old Dataset of the mutation.
func withDataset(node *Dataset) datasetOption {
	return func(m *DatasetMutation) {
		m.oldValue = func(context.Context) (*Dataset, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DatasetMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DatasetMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DatasetMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DatasetMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Dataset.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *DatasetMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *DatasetMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Dataset entity.
// If the Dataset object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DatasetMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *DatasetMutation) ResetName() {
	m.name = nil
}

// SetSourceType sets the "source_type" field.
func (m *DatasetMutation) SetSourceType(dt dataset.SourceType) {
	m.source_type = &dt
}

// SourceType returns the value of the "source_type" field in the mutation.
func (m *DatasetMutation) SourceType() (r dataset.SourceType, exists bool) {
	v := m.source_type
	if v == nil {
		return
	}
	return *v, true
}

// OldSourceType returns the old "source_type" field's value of the Dataset entity.
// If the Dataset object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DatasetMutation) OldSourceType(ctx context.Context) (v dataset.SourceType, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSourceType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSourceType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSourceType: %w", err)
	}
	return oldValue.SourceType, nil
}

// ResetSourceType resets all changes to the "source_type" field.
func (m *DatasetMutation) ResetSourceType() {
	m.source_type = nil
}

// SetConnectionDetails sets the "connection_details" field.
func (m *DatasetMutation) SetConnectionDetails(s string) {
	m.connection_details = &s
}

// ConnectionDetails returns the value of the "connection_details" field in the mutation.
func (m *DatasetMutation) ConnectionDetails() (r string, exists bool) {
	v := m.connection_details
	if v == nil {
		return
	}
	return *v, true
}

// OldConnectionDetails returns the old "connection_details" field's value of the Dataset entity.
// If the Dataset object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DatasetMutation) OldConnectionDetails(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldConnectionDetails is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldConnectionDetails requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldConnectionDetails: %w", err)
	}
	return oldValue.ConnectionDetails, nil
}

// ResetConnectionDetails resets all changes to the "connection_details" field.
func (m *DatasetMutation) ResetConnectionDetails() {
	m.connection_details = nil
}

// AddChartIDs adds the "charts" edge to the Chart entity by ids.
func (m *DatasetMutation) AddChartIDs(ids ...int) {
	if m.charts == nil {
		m.charts = make(map[int]struct{})
	}
	for i := range ids {
		m.charts[ids[i]] = struct{}{}
	}
}

// ClearCharts clears the "charts" edge to the Chart entity.
func (m *DatasetMutation) ClearCharts() {
	m.clearedcharts = true
}

// ChartsCleared reports if the "charts" edge to the Chart entity was cleared.
func (m *DatasetMutation) ChartsCleared() bool {
	return m.clearedcharts
}

// RemoveChartIDs removes the "charts" edge to the Chart entity by IDs.
func (m *DatasetMutation) RemoveChartIDs(ids ...int) {
	if m.removedcharts == nil {
		m.removedcharts = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.charts, ids[i])
		m.removedcharts[ids[i]] = struct{}{}
	}
}

// RemovedCharts returns the removed IDs of the "charts" edge to the Chart entity.
func (m *DatasetMutation) RemovedChartsIDs() (ids []int) {
	for id := range m.removedcharts {
		ids = append(ids, id)
	}
	return
}

// ChartsIDs returns the "charts" edge IDs in the mutation.
func (m *DatasetMutation) ChartsIDs() (ids []int) {
	for id := range m.charts {
		ids = append(ids, id)
	}
	return
}

// ResetCharts resets all changes to the "charts" edge.
func (m *DatasetMutation) ResetCharts() {
	m.charts = nil
	m.clearedcharts = false
	m.removedcharts = nil
}

// AddRlsRuleIDs adds the "rls_rules" edge to the RlsRule entity by ids.
func (m *DatasetMutation) AddRlsRuleIDs(ids ...int) {
	if m.rls_rules == nil {
		m.rls_rules = make(map[int]struct{})
	}
	for i := range ids {
		m.rls_rules[ids[i]] = struct{}{}
	}
}

// ClearRlsRules clears the "rls_rules" edge to the RlsRule entity.
func (m *DatasetMutation) ClearRlsRules() {
	m.clearedrls_rules = true
}

// RlsRulesCleared reports if the "rls_rules" edge to the RlsRule entity was cleared.
func (m *DatasetMutation) RlsRulesCleared() bool {
	return m.clearedrls_rules
}

// RemoveRlsRuleIDs removes the "rls_rules" edge to the RlsRule entity by IDs.
func (m *DatasetMutation) RemoveRlsRuleIDs(ids ...int) {
	if m.removedrls_rules == nil {
		m.removedrls_rules = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.rls_rules, ids[i])
		m.removedrls_rules[ids[i]] = struct{}{}
	}
}

// RemovedRlsRules returns the removed IDs of the "rls_rules" edge to the RlsRule entity.
func (m *DatasetMutation) RemovedRlsRulesIDs() (ids []int) {
	for id := range m.removedrls_rules {
		ids = append(ids, id)
	}
	return
}

// RlsRulesIDs returns the "rls_rules" edge IDs in the mutation.
func (m *DatasetMutation) RlsRulesIDs() (ids []int) {
	for id := range m.rls_rules {
		ids = append(ids, id)
	}
	return
}

// ResetRlsRules resets all changes to the "rls_rules" edge.
func (m *DatasetMutation) ResetRlsRules() {
	m.rls_rules = nil
	m.clearedrls_rules = false
	m.removedrls_rules = nil
}

// Where appends a list predicates to the DatasetMutation builder.
func (m *DatasetMutation) Where(ps ...predicate.Dataset) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DatasetMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DatasetMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Dataset, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DatasetMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DatasetMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Dataset).
func (m *DatasetMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DatasetMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, dataset.FieldName)
	}
	if m.source_type != nil {
		fields = append(fields, dataset.FieldSourceType)
	}
	if m.connection_details != nil {
		fields = append(fields, dataset.FieldConnectionDetails)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DatasetMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dataset.FieldName:
		return m.Name()
	case dataset.FieldSourceType:
		return m.SourceType()
	case dataset.FieldConnectionDetails:
		return m.ConnectionDetails()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DatasetMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dataset.FieldName:
		return m.OldName(ctx)
	case dataset.FieldSourceType:
		return m.OldSourceType(ctx)
	case dataset.FieldConnectionDetails:
		return m.OldConnectionDetails(ctx)
	}
	return nil, fmt.Errorf("unknown Dataset field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DatasetMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dataset.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case dataset.FieldSourceType:
		v, ok := value.(dataset.SourceType)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSourceType(v)
		return nil
	case dataset.FieldConnectionDetails:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetConnectionDetails(v)
		return nil
	}
	return fmt.Errorf("unknown Dataset field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DatasetMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DatasetMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DatasetMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Dataset numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DatasetMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DatasetMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DatasetMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Dataset nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DatasetMutation) ResetField(name string) error {
	switch name {
	case dataset.FieldName:
		m.ResetName()
		return nil
	case dataset.FieldSourceType:
		m.ResetSourceType()
		return nil
	case dataset.FieldConnectionDetails:
		m.ResetConnectionDetails()
		return nil
	}
	return fmt.Errorf("unknown Dataset field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DatasetMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.charts != nil {
		edges = append(edges, dataset.EdgeCharts)
	}
	if m.rls_rules != nil {
		edges = append(edges, dataset.EdgeRlsRules)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DatasetMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case dataset.EdgeCharts:
		ids := make([]ent.Value, 0, len(m.charts))
		for id := range m.charts {
			ids = append(ids, id)
		}
		return ids
	case dataset.EdgeRlsRules:
		ids := make([]ent.Value, 0, len(m.rls_rules))
		for id := range m.rls_rules {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DatasetMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedcharts != nil {
		edges = append(edges, dataset.EdgeCharts)
	}
	if m.removedrls_rules != nil {
		edges = append(edges, dataset.EdgeRlsRules)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DatasetMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case dataset.EdgeCharts:
		ids := make([]ent.Value, 0, len(m.removedcharts))
		for id := range m.removedcharts {
			ids = append(ids, id)
		}
		return ids
	case dataset.EdgeRlsRules:
		ids := make([]ent.Value, 0, len(m.removedrls_rules))
		for id := range m.removedrls_rules {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DatasetMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedcharts {
		edges = append(edges, dataset.EdgeCharts)
	}
	if m.clearedrls_rules {
		edges = append(edges, dataset.EdgeRlsRules)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DatasetMutation) EdgeCleared(name string) bool {
	switch name {
	case dataset.EdgeCharts:
		return m.clearedcharts
	case dataset.EdgeRlsRules:
		return m.clearedrls_rules
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DatasetMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Dataset unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DatasetMutation) ResetEdge(name string) error {
	switch name {
	case dataset.EdgeCharts:
		m.ResetCharts()
		return nil
	case dataset.EdgeRlsRules:
		m.ResetRlsRules()
		return nil
	}
	return fmt.Errorf("unknown Dataset edge %s", name)
}

// RlsRuleMutation represents an operation that mutates the RlsRule nodes in the graph.
type RlsRuleMutation struct {
	config
	op             Op
	typ            string
	id             *int
	name           *string
	target_table   *string
	sql_predicate  *string
	clearedFields  map[string]struct{}
	dataset        *int
	cleareddataset bool
	done           bool
	oldValue       func(context.Context) (*RlsRule, error)
	predicates     []predicate.RlsRule
}

var _ ent.Mutation = (*RlsRuleMutation)(nil)

// rlsruleOption allows management of the mutation configuration using functional options.
type rlsruleOption func(*RlsRuleMutation)

// newRlsRuleMutation creates new mutation for the RlsRule entity.
func newRlsRuleMutation(c config, op Op, opts ...rlsruleOption) *RlsRuleMutation {
	m := &RlsRuleMutation{
		config:        c,
		op:            op,
		typ:           TypeRlsRule,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRlsRuleID sets the ID field of the mutation.
func withRlsRuleID(id int) rlsruleOption {
	return func(m *RlsRuleMutation) {
		var (
			err   error
			once  sync.Once
			value *RlsRule
		)
		m.oldValue = func(ctx context.Context) (*RlsRule, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RlsRule.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRlsRule sets the old RlsRule of the mutation.
func withRlsRule(node *RlsRule) rlsruleOption {
	return func(m *RlsRuleMutation) {
		m.oldValue = func(context.Context) (*RlsRule, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RlsRuleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RlsRuleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RlsRuleMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RlsRuleMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RlsRule.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *RlsRuleMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *RlsRuleMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the RlsRule entity.
// If the RlsRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RlsRuleMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *RlsRuleMutation) ResetName() {
	m.name = nil
}

// SetTargetTable sets the "target_table" field.
func (m *RlsRuleMutation) SetTargetTable(s string) {
	m.target_table = &s
}

// TargetTable returns the value of the "target_table" field in the mutation.
func (m *RlsRuleMutation) TargetTable() (r string, exists bool) {
	v := m.target_table
	if v == nil {
		return
	}
	return *v, true
}

// OldTargetTable returns the old "target_table" field's value of the RlsRule entity.
// If the RlsRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RlsRuleMutation) OldTargetTable(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTargetTable is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTargetTable requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTargetTable: %w", err)
	}
	return oldValue.TargetTable, nil
}

// ResetTargetTable resets all changes to the "target_table" field.
func (m *RlsRuleMutation) ResetTargetTable() {
	m.target_table = nil
}

// SetSQLPredicate sets the "sql_predicate" field.
func (m *RlsRuleMutation) SetSQLPredicate(s string) {
	m.sql_predicate = &s
}

// SQLPredicate returns the value of the "sql_predicate" field in the mutation.
func (m *RlsRuleMutation) SQLPredicate() (r string, exists bool) {
	v := m.sql_predicate
	if v == nil {
		return
	}
	return *v, true
}

// OldSQLPredicate returns the old "sql_predicate" field's value of the RlsRule entity.
// If the RlsRule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RlsRuleMutation) OldSQLPredicate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSQLPredicate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSQLPredicate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSQLPredicate: %w", err)
	}
	return oldValue.SQLPredicate, nil
}

// ResetSQLPredicate resets all changes to the "sql_predicate" field.
func (m *RlsRuleMutation) ResetSQLPredicate() {
	m.sql_predicate = nil
}

// SetDatasetID sets the "dataset" edge to the Dataset entity by id.
func (m *RlsRuleMutation) SetDatasetID(id int) {
	m.dataset = &id
}

// ClearDataset clears the "dataset" edge to the Dataset entity.
func (m *RlsRuleMutation) ClearDataset() {
	m.cleareddataset = true
}

// DatasetCleared reports if the "dataset" edge to the Dataset entity was cleared.
func (m *RlsRuleMutation) DatasetCleared() bool {
	return m.cleareddataset
}

// DatasetID returns the "dataset" edge ID in the mutation.
func (m *RlsRuleMutation) DatasetID() (id int, exists bool) {
	if m.dataset != nil {
		return *m.dataset, true
	}
	return
}

// DatasetIDs returns the "dataset" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// DatasetID instead. It exists only for internal usage by the builders.
func (m *RlsRuleMutation) DatasetIDs() (ids []int) {
	if id := m.dataset; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetDataset resets all changes to the "dataset" edge.
func (m *RlsRuleMutation) ResetDataset() {
	m.dataset = nil
	m.cleareddataset = false
}

// Where appends a list predicates to the RlsRuleMutation builder.
func (m *RlsRuleMutation) Where(ps ...predicate.RlsRule) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RlsRuleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RlsRuleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RlsRule, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RlsRuleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RlsRuleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RlsRule).
func (m *RlsRuleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RlsRuleMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, rlsrule.FieldName)
	}
	if m.target_table != nil {
		fields = append(fields, rlsrule.FieldTargetTable)
	}
	if m.sql_predicate != nil {
		fields = append(fields, rlsrule.FieldSQLPredicate)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RlsRuleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case rlsrule.FieldName:
		return m.Name()
	case rlsrule.FieldTargetTable:
		return m.TargetTable()
	case rlsrule.FieldSQLPredicate:
		return m.SQLPredicate()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RlsRuleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case rlsrule.FieldName:
		return m.OldName(ctx)
	case rlsrule.FieldTargetTable:
		return m.OldTargetTable(ctx)
	case rlsrule.FieldSQLPredicate:
		return m.OldSQLPredicate(ctx)
	}
	return nil, fmt.Errorf("unknown RlsRule field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RlsRuleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case rlsrule.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case rlsrule.FieldTargetTable:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTargetTable(v)
		return nil
	case rlsrule.FieldSQLPredicate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSQLPredicate(v)
		return nil
	}
	return fmt.Errorf("unknown RlsRule field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RlsRuleMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RlsRuleMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RlsRuleMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RlsRule numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RlsRuleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RlsRuleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RlsRuleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RlsRule nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RlsRuleMutation) ResetField(name string) error {
	switch name {
	case rlsrule.FieldName:
		m.ResetName()
		return nil
	case rlsrule.FieldTargetTable:
		m.ResetTargetTable()
		return nil
	case rlsrule.FieldSQLPredicate:
		m.ResetSQLPredicate()
		return nil
	}
	return fmt.Errorf("unknown RlsRule field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RlsRuleMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.dataset != nil {
		edges = append(edges, rlsrule.EdgeDataset)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RlsRuleMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case rlsrule.EdgeDataset:
		if id := m.dataset; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RlsRuleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RlsRuleMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RlsRuleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleareddataset {
		edges = append(edges, rlsrule.EdgeDataset)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RlsRuleMutation) EdgeCleared(name string) bool {
	switch name {
	case rlsrule.EdgeDataset:
		return m.cleareddataset
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RlsRuleMutation) ClearEdge(name string) error {
	switch name {
	case rlsrule.EdgeDataset:
		m.ClearDataset()
		return nil
	}
	return fmt.Errorf("unknown RlsRule unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RlsRuleMutation) ResetEdge(name string) error {
	switch name {
	case rlsrule.EdgeDataset:
		m.ResetDataset()
		return nil
	}
	return fmt.Errorf("unknown RlsRule edge %s", name)
}
