// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/dataset"
	"bi-metadata/ent/rlsrule"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RlsRuleCreate is the builder for creating a RlsRule entity.
type RlsRuleCreate struct {
	config
	mutation *RlsRuleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RlsRuleCreate) SetName(v string) *RlsRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTargetTable sets the "target_table" field.
func (_c *RlsRuleCreate) SetTargetTable(v string) *RlsRuleCreate {
	_c.mutation.SetTargetTable(v)
	return _c
}

// SetSQLPredicate sets the "sql_predicate" field.
func (_c *RlsRuleCreate) SetSQLPredicate(v string) *RlsRuleCreate {
	_c.mutation.SetSQLPredicate(v)
	return _c
}

// SetDatasetID sets the "dataset" edge to the Dataset entity by ID.
func (_c *RlsRuleCreate) SetDatasetID(id int) *RlsRuleCreate {
	_c.mutation.SetDatasetID(id)
	return _c
}

// SetNillableDatasetID sets the "dataset" edge to the Dataset entity by ID if the given value is not nil.
func (_c *RlsRuleCreate) SetNillableDatasetID(id *int) *RlsRuleCreate {
	if id != nil {
		_c = _c.SetDatasetID(*id)
	}
	return _c
}

// SetDataset sets the "dataset" edge to the Dataset entity.
func (_c *RlsRuleCreate) SetDataset(v *Dataset) *RlsRuleCreate {
	return _c.SetDatasetID(v.ID)
}

// Mutation returns the RlsRuleMutation object of the builder.
func (_c *RlsRuleCreate) Mutation() *RlsRuleMutation {
	return _c.mutation
}

// Save creates the RlsRule in the database.
func (_c *RlsRuleCreate) Save(ctx context.Context) (*RlsRule, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RlsRuleCreate) SaveX(ctx context.Context) *RlsRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RlsRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RlsRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RlsRuleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RlsRule.name"`)}
	}
	if _, ok := _c.mutation.TargetTable(); !ok {
		return &ValidationError{Name: "target_table", err: errors.New(`ent: missing required field "RlsRule.target_table"`)}
	}
	if _, ok := _c.mutation.SQLPredicate(); !ok {
		return &ValidationError{Name: "sql_predicate", err: errors.New(`ent: missing required field "RlsRule.sql_predicate"`)}
	}
	return nil
}

func (_c *RlsRuleCreate) sqlSave(ctx context.Context) (*RlsRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RlsRuleCreate) createSpec() (*RlsRule, *sqlgraph.CreateSpec) {
	var (
		_node = &RlsRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rlsrule.Table, sqlgraph.NewFieldSpec(rlsrule.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(rlsrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TargetTable(); ok {
		_spec.SetField(rlsrule.FieldTargetTable, field.TypeString, value)
		_node.TargetTable = value
	}
	if value, ok := _c.mutation.SQLPredicate(); ok {
		_spec.SetField(rlsrule.FieldSQLPredicate, field.TypeString, value)
		_node.SQLPredicate = value
	}
	if nodes := _c.mutation.DatasetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rlsrule.DatasetTable,
			Columns: []string{rlsrule.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.dataset_rls_rules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RlsRuleCreateBulk is the builder for creating many RlsRule entities in bulk.
type RlsRuleCreateBulk struct {
	config
	err      error
	builders []*RlsRuleCreate
}

// Save creates the RlsRule entities in the database.
func (_c *RlsRuleCreateBulk) Save(ctx context.Context) ([]*RlsRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RlsRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RlsRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RlsRuleCreateBulk) SaveX(ctx context.Context) []*RlsRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RlsRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RlsRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
