// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/dataset"
	"bi-metadata/ent/predicate"
	"bi-metadata/ent/rlsrule"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RlsRuleUpdate is the builder for updating RlsRule entities.
type RlsRuleUpdate struct {
	config
	hooks    []Hook
	mutation *RlsRuleMutation
}

// Where appends a list predicates to the RlsRuleUpdate builder.
func (_u *RlsRuleUpdate) Where(ps ...predicate.RlsRule) *RlsRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RlsRuleUpdate) SetName(v string) *RlsRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RlsRuleUpdate) SetNillableName(v *string) *RlsRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTargetTable sets the "target_table" field.
func (_u *RlsRuleUpdate) SetTargetTable(v string) *RlsRuleUpdate {
	_u.mutation.SetTargetTable(v)
	return _u
}

// SetNillableTargetTable sets the "target_table" field if the given value is not nil.
func (_u *RlsRuleUpdate) SetNillableTargetTable(v *string) *RlsRuleUpdate {
	if v != nil {
		_u.SetTargetTable(*v)
	}
	return _u
}

// SetSQLPredicate sets the "sql_predicate" field.
func (_u *RlsRuleUpdate) SetSQLPredicate(v string) *RlsRuleUpdate {
	_u.mutation.SetSQLPredicate(v)
	return _u
}

// SetNillableSQLPredicate sets the "sql_predicate" field if the given value is not nil.
func (_u *RlsRuleUpdate) SetNillableSQLPredicate(v *string) *RlsRuleUpdate {
	if v != nil {
		_u.SetSQLPredicate(*v)
	}
	return _u
}

// SetDatasetID sets the "dataset" edge to the Dataset entity by ID.
func (_u *RlsRuleUpdate) SetDatasetID(id int) *RlsRuleUpdate {
	_u.mutation.SetDatasetID(id)
	return _u
}

// SetNillableDatasetID sets the "dataset" edge to the Dataset entity by ID if the given value is not nil.
func (_u *RlsRuleUpdate) SetNillableDatasetID(id *int) *RlsRuleUpdate {
	if id != nil {
		_u = _u.SetDatasetID(*id)
	}
	return _u
}

// SetDataset sets the "dataset" edge to the Dataset entity.
func (_u *RlsRuleUpdate) SetDataset(v *Dataset) *RlsRuleUpdate {
	return _u.SetDatasetID(v.ID)
}

// Mutation returns the RlsRuleMutation object of the builder.
func (_u *RlsRuleUpdate) Mutation() *RlsRuleMutation {
	return _u.mutation
}

// ClearDataset clears the "dataset" edge to the Dataset entity.
func (_u *RlsRuleUpdate) ClearDataset() *RlsRuleUpdate {
	_u.mutation.ClearDataset()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RlsRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RlsRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RlsRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RlsRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RlsRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(rlsrule.Table, rlsrule.Columns, sqlgraph.NewFieldSpec(rlsrule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rlsrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetTable(); ok {
		_spec.SetField(rlsrule.FieldTargetTable, field.TypeString, value)
	}
	if value, ok := _u.mutation.SQLPredicate(); ok {
		_spec.SetField(rlsrule.FieldSQLPredicate, field.TypeString, value)
	}
	if _u.mutation.DatasetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rlsrule.DatasetTable,
			Columns: []string{rlsrule.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DatasetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rlsrule.DatasetTable,
			Columns: []string{rlsrule.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rlsrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RlsRuleUpdateOne is the builder for updating a single RlsRule entity.
type RlsRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RlsRuleMutation
}

// SetName sets the "name" field.
func (_u *RlsRuleUpdateOne) SetName(v string) *RlsRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RlsRuleUpdateOne) SetNillableName(v *string) *RlsRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTargetTable sets the "target_table" field.
func (_u *RlsRuleUpdateOne) SetTargetTable(v string) *RlsRuleUpdateOne {
	_u.mutation.SetTargetTable(v)
	return _u
}

// SetNillableTargetTable sets the "target_table" field if the given value is not nil.
func (_u *RlsRuleUpdateOne) SetNillableTargetTable(v *string) *RlsRuleUpdateOne {
	if v != nil {
		_u.SetTargetTable(*v)
	}
	return _u
}

// SetSQLPredicate sets the "sql_predicate" field.
func (_u *RlsRuleUpdateOne) SetSQLPredicate(v string) *RlsRuleUpdateOne {
	_u.mutation.SetSQLPredicate(v)
	return _u
}

// SetNillableSQLPredicate sets the "sql_predicate" field if the given value is not nil.
func (_u *RlsRuleUpdateOne) SetNillableSQLPredicate(v *string) *RlsRuleUpdateOne {
	if v != nil {
		_u.SetSQLPredicate(*v)
	}
	return _u
}

// SetDatasetID sets the "dataset" edge to the Dataset entity by ID.
func (_u *RlsRuleUpdateOne) SetDatasetID(id int) *RlsRuleUpdateOne {
	_u.mutation.SetDatasetID(id)
	return _u
}

// SetNillableDatasetID sets the "dataset" edge to the Dataset entity by ID if the given value is not nil.
func (_u *RlsRuleUpdateOne) SetNillableDatasetID(id *int) *RlsRuleUpdateOne {
	if id != nil {
		_u = _u.SetDatasetID(*id)
	}
	return _u
}

// SetDataset sets the "dataset" edge to the Dataset entity.
func (_u *RlsRuleUpdateOne) SetDataset(v *Dataset) *RlsRuleUpdateOne {
	return _u.SetDatasetID(v.ID)
}

// Mutation returns the RlsRuleMutation object of the builder.
func (_u *RlsRuleUpdateOne) Mutation() *RlsRuleMutation {
	return _u.mutation
}

// ClearDataset clears the "dataset" edge to the Dataset entity.
func (_u *RlsRuleUpdateOne) ClearDataset() *RlsRuleUpdateOne {
	_u.mutation.ClearDataset()
	return _u
}

// Where appends a list predicates to the RlsRuleUpdate builder.
func (_u *RlsRuleUpdateOne) Where(ps ...predicate.RlsRule) *RlsRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RlsRuleUpdateOne) Select(field string, fields ...string) *RlsRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RlsRule entity.
func (_u *RlsRuleUpdateOne) Save(ctx context.Context) (*RlsRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RlsRuleUpdateOne) SaveX(ctx context.Context) *RlsRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RlsRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RlsRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RlsRuleUpdateOne) sqlSave(ctx context.Context) (_node *RlsRule, err error) {
	_spec := sqlgraph.NewUpdateSpec(rlsrule.Table, rlsrule.Columns, sqlgraph.NewFieldSpec(rlsrule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RlsRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rlsrule.FieldID)
		for _, f := range fields {
			if !rlsrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rlsrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rlsrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetTable(); ok {
		_spec.SetField(rlsrule.FieldTargetTable, field.TypeString, value)
	}
	if value, ok := _u.mutation.SQLPredicate(); ok {
		_spec.SetField(rlsrule.FieldSQLPredicate, field.TypeString, value)
	}
	if _u.mutation.DatasetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rlsrule.DatasetTable,
			Columns: []string{rlsrule.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DatasetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rlsrule.DatasetTable,
			Columns: []string{rlsrule.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RlsRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rlsrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
