// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/predicate"
	"bi-metadata/ent/rlsrule"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RlsRuleDelete is the builder for deleting a RlsRule entity.
type RlsRuleDelete struct {
	config
	hooks    []Hook
	mutation *RlsRuleMutation
}

// Where appends a list predicates to the RlsRuleDelete builder.
func (_d *RlsRuleDelete) Where(ps ...predicate.RlsRule) *RlsRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RlsRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RlsRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RlsRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rlsrule.Table, sqlgraph.NewFieldSpec(rlsrule.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RlsRuleDeleteOne is the builder for deleting a single RlsRule entity.
type RlsRuleDeleteOne struct {
	_d *RlsRuleDelete
}

// Where appends a list predicates to the RlsRuleDelete builder.
func (_d *RlsRuleDeleteOne) Where(ps ...predicate.RlsRule) *RlsRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RlsRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rlsrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RlsRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
