// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-metadata/ent/dataset"
	"bi-metadata/ent/rlsrule"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RlsRule is the model entity for the RlsRule schema.
type RlsRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// TargetTable holds the value of the "target_table" field.
	TargetTable string `json:"target_table,omitempty"`
	// SQLPredicate holds the value of the "sql_predicate" field.
	SQLPredicate string `json:"sql_predicate,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RlsRuleQuery when eager-loading is set.
	Edges             RlsRuleEdges `json:"edges"`
	dataset_rls_rules *int
	selectValues      sql.SelectValues
}

// RlsRuleEdges holds the relations/edges for other nodes in the graph.
type RlsRuleEdges struct {
	// Dataset holds the value of the dataset edge.
	Dataset *Dataset `json:"dataset,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DatasetOrErr returns the Dataset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RlsRuleEdges) DatasetOrErr() (*Dataset, error) {
	if e.Dataset != nil {
		return e.Dataset, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: dataset.Label}
	}
	return nil, &NotLoadedError{edge: "dataset"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RlsRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rlsrule.FieldID:
			values[i] = new(sql.NullInt64)
		case rlsrule.FieldName, rlsrule.FieldTargetTable, rlsrule.FieldSQLPredicate:
			values[i] = new(sql.NullString)
		case rlsrule.ForeignKeys[0]: // dataset_rls_rules
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RlsRule fields.
func (_m *RlsRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rlsrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case rlsrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case rlsrule.FieldTargetTable:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_table", values[i])
			} else if value.Valid {
				_m.TargetTable = value.String
			}
		case rlsrule.FieldSQLPredicate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sql_predicate", values[i])
			} else if value.Valid {
				_m.SQLPredicate = value.String
			}
		case rlsrule.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field dataset_rls_rules", value)
			} else if value.Valid {
				_m.dataset_rls_rules = new(int)
				*_m.dataset_rls_rules = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RlsRule.
// This includes values selected through modifiers, order, etc.
func (_m *RlsRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDataset queries the "dataset" edge of the RlsRule entity.
func (_m *RlsRule) QueryDataset() *DatasetQuery {
	return NewRlsRuleClient(_m.config).QueryDataset(_m)
}

// Update returns a builder for updating this RlsRule.
// Note that you need to call RlsRule.Unwrap() before calling this method if this RlsRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RlsRule) Update() *RlsRuleUpdateOne {
	return NewRlsRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RlsRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RlsRule) Unwrap() *RlsRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RlsRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RlsRule) String() string {
	var builder strings.Builder
	builder.WriteString("RlsRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("target_table=")
	builder.WriteString(_m.TargetTable)
	builder.WriteString(", ")
	builder.WriteString("sql_predicate=")
	builder.WriteString(_m.SQLPredicate)
	builder.WriteByte(')')
	return builder.String()
}

// RlsRules is a parsable slice of RlsRule.
type RlsRules []*RlsRule
