// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-gateway/ent/permission"
	"bi-gateway/ent/predicate"
	"bi-gateway/ent/role"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PermissionUpdate is the builder for updating Permission entities.
type PermissionUpdate struct {
	config
	hooks    []Hook
	mutation *PermissionMutation
}

// Where appends a list predicates to the PermissionUpdate builder.
func (_u *PermissionUpdate) Where(ps ...predicate.Permission) *PermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccessLevel sets the "access_level" field.
func (_u *PermissionUpdate) SetAccessLevel(v permission.AccessLevel) *PermissionUpdate {
	_u.mutation.SetAccessLevel(v)
	return _u
}

// SetNillableAccessLevel sets the "access_level" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableAccessLevel(v *permission.AccessLevel) *PermissionUpdate {
	if v != nil {
		_u.SetAccessLevel(*v)
	}
	return _u
}

// SetObjectID sets the "object_id" field.
func (_u *PermissionUpdate) SetObjectID(v int) *PermissionUpdate {
	_u.mutation.ResetObjectID()
	_u.mutation.SetObjectID(v)
	return _u
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableObjectID(v *int) *PermissionUpdate {
	if v != nil {
		_u.SetObjectID(*v)
	}
	return _u
}

// AddObjectID adds value to the "object_id" field.
func (_u *PermissionUpdate) AddObjectID(v int) *PermissionUpdate {
	_u.mutation.AddObjectID(v)
	return _u
}

// ClearObjectID clears the value of the "object_id" field.
func (_u *PermissionUpdate) ClearObjectID() *PermissionUpdate {
	_u.mutation.ClearObjectID()
	return _u
}

// SetObjectType sets the "object_type" field.
func (_u *PermissionUpdate) SetObjectType(v string) *PermissionUpdate {
	_u.mutation.SetObjectType(v)
	return _u
}

// SetNillableObjectType sets the "object_type" field if the given value is not nil.
func (_u *PermissionUpdate) SetNillableObjectType(v *string) *PermissionUpdate {
	if v != nil {
		_u.SetObjectType(*v)
	}
	return _u
}

// ClearObjectType clears the value of the "object_type" field.
func (_u *PermissionUpdate) ClearObjectType() *PermissionUpdate {
	_u.mutation.ClearObjectType()
	return _u
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *PermissionUpdate) AddRoleIDs(ids ...int) *PermissionUpdate {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *PermissionUpdate) AddRoles(v ...*Role) *PermissionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// Mutation returns the PermissionMutation object of the builder.
func (_u *PermissionUpdate) Mutation() *PermissionMutation {
	return _u.mutation
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *PermissionUpdate) ClearRoles() *PermissionUpdate {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *PermissionUpdate) RemoveRoleIDs(ids ...int) *PermissionUpdate {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *PermissionUpdate) RemoveRoles(v ...*Role) *PermissionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionUpdate) check() error {
	if v, ok := _u.mutation.AccessLevel(); ok {
		if err := permission.AccessLevelValidator(v); err != nil {
			return &ValidationError{Name: "access_level", err: fmt.Errorf(`ent: validator failed for field "Permission.access_level": %w`, err)}
		}
	}
	return nil
}

func (_u *PermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permission.Table, permission.Columns, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccessLevel(); ok {
		_spec.SetField(permission.FieldAccessLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ObjectID(); ok {
		_spec.SetField(permission.FieldObjectID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedObjectID(); ok {
		_spec.AddField(permission.FieldObjectID, field.TypeInt, value)
	}
	if _u.mutation.ObjectIDCleared() {
		_spec.ClearField(permission.FieldObjectID, field.TypeInt)
	}
	if value, ok := _u.mutation.ObjectType(); ok {
		_spec.SetField(permission.FieldObjectType, field.TypeString, value)
	}
	if _u.mutation.ObjectTypeCleared() {
		_spec.ClearField(permission.FieldObjectType, field.TypeString)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   permission.RolesTable,
			Columns: permission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   permission.RolesTable,
			Columns: permission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   permission.RolesTable,
			Columns: permission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PermissionUpdateOne is the builder for updating a single Permission entity.
type PermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PermissionMutation
}

// SetAccessLevel sets the "access_level" field.
func (_u *PermissionUpdateOne) SetAccessLevel(v permission.AccessLevel) *PermissionUpdateOne {
	_u.mutation.SetAccessLevel(v)
	return _u
}

// SetNillableAccessLevel sets the "access_level" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableAccessLevel(v *permission.AccessLevel) *PermissionUpdateOne {
	if v != nil {
		_u.SetAccessLevel(*v)
	}
	return _u
}

// SetObjectID sets the "object_id" field.
func (_u *PermissionUpdateOne) SetObjectID(v int) *PermissionUpdateOne {
	_u.mutation.ResetObjectID()
	_u.mutation.SetObjectID(v)
	return _u
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableObjectID(v *int) *PermissionUpdateOne {
	if v != nil {
		_u.SetObjectID(*v)
	}
	return _u
}

// AddObjectID adds value to the "object_id" field.
func (_u *PermissionUpdateOne) AddObjectID(v int) *PermissionUpdateOne {
	_u.mutation.AddObjectID(v)
	return _u
}

// ClearObjectID clears the value of the "object_id" field.
func (_u *PermissionUpdateOne) ClearObjectID() *PermissionUpdateOne {
	_u.mutation.ClearObjectID()
	return _u
}

// SetObjectType sets the "object_type" field.
func (_u *PermissionUpdateOne) SetObjectType(v string) *PermissionUpdateOne {
	_u.mutation.SetObjectType(v)
	return _u
}

// SetNillableObjectType sets the "object_type" field if the given value is not nil.
func (_u *PermissionUpdateOne) SetNillableObjectType(v *string) *PermissionUpdateOne {
	if v != nil {
		_u.SetObjectType(*v)
	}
	return _u
}

// ClearObjectType clears the value of the "object_type" field.
func (_u *PermissionUpdateOne) ClearObjectType() *PermissionUpdateOne {
	_u.mutation.ClearObjectType()
	return _u
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *PermissionUpdateOne) AddRoleIDs(ids ...int) *PermissionUpdateOne {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *PermissionUpdateOne) AddRoles(v ...*Role) *PermissionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// Mutation returns the PermissionMutation object of the builder.
func (_u *PermissionUpdateOne) Mutation() *PermissionMutation {
	return _u.mutation
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *PermissionUpdateOne) ClearRoles() *PermissionUpdateOne {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *PermissionUpdateOne) RemoveRoleIDs(ids ...int) *PermissionUpdateOne {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *PermissionUpdateOne) RemoveRoles(v ...*Role) *PermissionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// Where appends a list predicates to the PermissionUpdate builder.
func (_u *PermissionUpdateOne) Where(ps ...predicate.Permission) *PermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PermissionUpdateOne) Select(field string, fields ...string) *PermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Permission entity.
func (_u *PermissionUpdateOne) Save(ctx context.Context) (*Permission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PermissionUpdateOne) SaveX(ctx context.Context) *Permission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PermissionUpdateOne) check() error {
	if v, ok := _u.mutation.AccessLevel(); ok {
		if err := permission.AccessLevelValidator(v); err != nil {
			return &ValidationError{Name: "access_level", err: fmt.Errorf(`ent: validator failed for field "Permission.access_level": %w`, err)}
		}
	}
	return nil
}

func (_u *PermissionUpdateOne) sqlSave(ctx context.Context) (_node *Permission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permission.Table, permission.Columns, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Permission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permission.FieldID)
		for _, f := range fields {
			if !permission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccessLevel(); ok {
		_spec.SetField(permission.FieldAccessLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ObjectID(); ok {
		_spec.SetField(permission.FieldObjectID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedObjectID(); ok {
		_spec.AddField(permission.FieldObjectID, field.TypeInt, value)
	}
	if _u.mutation.ObjectIDCleared() {
		_spec.ClearField(permission.FieldObjectID, field.TypeInt)
	}
	if value, ok := _u.mutation.ObjectType(); ok {
		_spec.SetField(permission.FieldObjectType, field.TypeString, value)
	}
	if _u.mutation.ObjectTypeCleared() {
		_spec.ClearField(permission.FieldObjectType, field.TypeString)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   permission.RolesTable,
			Columns: permission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   permission.RolesTable,
			Columns: permission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   permission.RolesTable,
			Columns: permission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Permission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
