// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bi-gateway/ent/schema"
	"bi-gateway/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[4].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
}
