// Code generated by ent, DO NOT EDIT.

package dashboard

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dashboard type in the database.
	Label = "dashboard"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLayout holds the string denoting the layout field in the database.
	FieldLayout = "layout"
	// EdgeCharts holds the string denoting the charts edge name in mutations.
	EdgeCharts = "charts"
	// Table holds the table name of the dashboard in the database.
	Table = "dashboards"
	// ChartsTable is the table that holds the charts relation/edge. The primary key declared below.
	ChartsTable = "chart_dashboards"
	// ChartsInverseTable is the table name for the Chart entity.
	// It exists in this package in order to avoid circular dependency with the "chart" package.
	ChartsInverseTable = "charts"
)

// Columns holds all SQL columns for dashboard fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldLayout,
}

var (
	// ChartsPrimaryKey and ChartsColumn2 are the table columns denoting the
	// primary key for the charts relation (M2M).
	ChartsPrimaryKey = []string{"chart_id", "dashboard_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Dashboard queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByChartsCount orders the results by charts count.
func ByChartsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChartsStep(), opts...)
	}
}

// ByCharts orders the results by charts terms.
func ByCharts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChartsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChartsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChartsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ChartsTable, ChartsPrimaryKey...),
	)
}
