// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChartsColumns holds the columns for the "charts" table.
	ChartsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "config", Type: field.TypeJSON},
		{Name: "column_styles", Type: field.TypeJSON},
		{Name: "dataset_charts", Type: field.TypeInt, Nullable: true},
	}
	// ChartsTable holds the schema information for the "charts" table.
	ChartsTable = &schema.Table{
		Name:       "charts",
		Columns:    ChartsColumns,
		PrimaryKey: []*schema.Column{ChartsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "charts_datasets_charts",
				Columns:    []*schema.Column{ChartsColumns[4]},
				RefColumns: []*schema.Column{DatasetsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DashboardsColumns holds the columns for the "dashboards" table.
	DashboardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "layout", Type: field.TypeJSON},
	}
	// DashboardsTable holds the schema information for the "dashboards" table.
	DashboardsTable = &schema.Table{
		Name:       "dashboards",
		Columns:    DashboardsColumns,
		PrimaryKey: []*schema.Column{DashboardsColumns[0]},
	}
	// DatasetsColumns holds the columns for the "datasets" table.
	DatasetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "source_type", Type: field.TypeEnum, Enums: []string{"DB", "API", "FILE"}},
		{Name: "connection_details", Type: field.TypeString},
	}
	// DatasetsTable holds the schema information for the "datasets" table.
	DatasetsTable = &schema.Table{
		Name:       "datasets",
		Columns:    DatasetsColumns,
		PrimaryKey: []*schema.Column{DatasetsColumns[0]},
	}
	// RlsRulesColumns holds the columns for the "rls_rules" table.
	RlsRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "target_table", Type: field.TypeString},
		{Name: "sql_predicate", Type: field.TypeString},
		{Name: "dataset_rls_rules", Type: field.TypeInt, Nullable: true},
	}
	// RlsRulesTable holds the schema information for the "rls_rules" table.
	RlsRulesTable = &schema.Table{
		Name:       "rls_rules",
		Columns:    RlsRulesColumns,
		PrimaryKey: []*schema.Column{RlsRulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rls_rules_datasets_rls_rules",
				Columns:    []*schema.Column{RlsRulesColumns[4]},
				RefColumns: []*schema.Column{DatasetsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ChartDashboardsColumns holds the columns for the "chart_dashboards" table.
	ChartDashboardsColumns = []*schema.Column{
		{Name: "chart_id", Type: field.TypeInt},
		{Name: "dashboard_id", Type: field.TypeInt},
	}
	// ChartDashboardsTable holds the schema information for the "chart_dashboards" table.
	ChartDashboardsTable = &schema.Table{
		Name:       "chart_dashboards",
		Columns:    ChartDashboardsColumns,
		PrimaryKey: []*schema.Column{ChartDashboardsColumns[0], ChartDashboardsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chart_dashboards_chart_id",
				Columns:    []*schema.Column{ChartDashboardsColumns[0]},
				RefColumns: []*schema.Column{ChartsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "chart_dashboards_dashboard_id",
				Columns:    []*schema.Column{ChartDashboardsColumns[1]},
				RefColumns: []*schema.Column{DashboardsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChartsTable,
		DashboardsTable,
		DatasetsTable,
		RlsRulesTable,
		ChartDashboardsTable,
	}
)

func init() {
	ChartsTable.ForeignKeys[0].RefTable = DatasetsTable
	RlsRulesTable.ForeignKeys[0].RefTable = DatasetsTable
	ChartDashboardsTable.ForeignKeys[0].RefTable = ChartsTable
	ChartDashboardsTable.ForeignKeys[1].RefTable = DashboardsTable
}
