// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chart is the predicate function for chart builders.
type Chart func(*sql.Selector)

// Dashboard is the predicate function for dashboard builders.
type Dashboard func(*sql.Selector)

// Dataset is the predicate function for dataset builders.
type Dataset func(*sql.Selector)

// RlsRule is the predicate function for rlsrule builders.
type RlsRule func(*sql.Selector)
