// Code generated by ent, DO NOT EDIT.

package permission

import (
	"bi-gateway/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldID, id))
}

// ObjectID applies equality check predicate on the "object_id" field. It's identical to ObjectIDEQ.
func ObjectID(v int) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldObjectID, v))
}

// ObjectType applies equality check predicate on the "object_type" field. It's identical to ObjectTypeEQ.
func ObjectType(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldObjectType, v))
}

// AccessLevelEQ applies the EQ predicate on the "access_level" field.
func AccessLevelEQ(v AccessLevel) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldAccessLevel, v))
}

// AccessLevelNEQ applies the NEQ predicate on the "access_level" field.
func AccessLevelNEQ(v AccessLevel) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldAccessLevel, v))
}

// AccessLevelIn applies the In predicate on the "access_level" field.
func AccessLevelIn(vs ...AccessLevel) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldAccessLevel, vs...))
}

// AccessLevelNotIn applies the NotIn predicate on the "access_level" field.
func AccessLevelNotIn(vs ...AccessLevel) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldAccessLevel, vs...))
}

// ObjectIDEQ applies the EQ predicate on the "object_id" field.
func ObjectIDEQ(v int) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldObjectID, v))
}

// ObjectIDNEQ applies the NEQ predicate on the "object_id" field.
func ObjectIDNEQ(v int) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldObjectID, v))
}

// ObjectIDIn applies the In predicate on the "object_id" field.
func ObjectIDIn(vs ...int) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldObjectID, vs...))
}

// ObjectIDNotIn applies the NotIn predicate on the "object_id" field.
func ObjectIDNotIn(vs ...int) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldObjectID, vs...))
}

// ObjectIDGT applies the GT predicate on the "object_id" field.
func ObjectIDGT(v int) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldObjectID, v))
}

// ObjectIDGTE applies the GTE predicate on the "object_id" field.
func ObjectIDGTE(v int) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldObjectID, v))
}

// ObjectIDLT applies the LT predicate on the "object_id" field.
func ObjectIDLT(v int) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldObjectID, v))
}

// ObjectIDLTE applies the LTE predicate on the "object_id" field.
func ObjectIDLTE(v int) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldObjectID, v))
}

// ObjectIDIsNil applies the IsNil predicate on the "object_id" field.
func ObjectIDIsNil() predicate.Permission {
	return predicate.Permission(sql.FieldIsNull(FieldObjectID))
}

// ObjectIDNotNil applies the NotNil predicate on the "object_id" field.
func ObjectIDNotNil() predicate.Permission {
	return predicate.Permission(sql.FieldNotNull(FieldObjectID))
}

// ObjectTypeEQ applies the EQ predicate on the "object_type" field.
func ObjectTypeEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEQ(FieldObjectType, v))
}

// ObjectTypeNEQ applies the NEQ predicate on the "object_type" field.
func ObjectTypeNEQ(v string) predicate.Permission {
	return predicate.Permission(sql.FieldNEQ(FieldObjectType, v))
}

// ObjectTypeIn applies the In predicate on the "object_type" field.
func ObjectTypeIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldIn(FieldObjectType, vs...))
}

// ObjectTypeNotIn applies the NotIn predicate on the "object_type" field.
func ObjectTypeNotIn(vs ...string) predicate.Permission {
	return predicate.Permission(sql.FieldNotIn(FieldObjectType, vs...))
}

// ObjectTypeGT applies the GT predicate on the "object_type" field.
func ObjectTypeGT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGT(FieldObjectType, v))
}

// ObjectTypeGTE applies the GTE predicate on the "object_type" field.
func ObjectTypeGTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldGTE(FieldObjectType, v))
}

// ObjectTypeLT applies the LT predicate on the "object_type" field.
func ObjectTypeLT(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLT(FieldObjectType, v))
}

// ObjectTypeLTE applies the LTE predicate on the "object_type" field.
func ObjectTypeLTE(v string) predicate.Permission {
	return predicate.Permission(sql.FieldLTE(FieldObjectType, v))
}

// ObjectTypeContains applies the Contains predicate on the "object_type" field.
func ObjectTypeContains(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContains(FieldObjectType, v))
}

// ObjectTypeHasPrefix applies the HasPrefix predicate on the "object_type" field.
func ObjectTypeHasPrefix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasPrefix(FieldObjectType, v))
}

// ObjectTypeHasSuffix applies the HasSuffix predicate on the "object_type" field.
func ObjectTypeHasSuffix(v string) predicate.Permission {
	return predicate.Permission(sql.FieldHasSuffix(FieldObjectType, v))
}

// ObjectTypeIsNil applies the IsNil predicate on the "object_type" field.
func ObjectTypeIsNil() predicate.Permission {
	return predicate.Permission(sql.FieldIsNull(FieldObjectType))
}

// ObjectTypeNotNil applies the NotNil predicate on the "object_type" field.
func ObjectTypeNotNil() predicate.Permission {
	return predicate.Permission(sql.FieldNotNull(FieldObjectType))
}

// ObjectTypeEqualFold applies the EqualFold predicate on the "object_type" field.
func ObjectTypeEqualFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldEqualFold(FieldObjectType, v))
}

// ObjectTypeContainsFold applies the ContainsFold predicate on the "object_type" field.
func ObjectTypeContainsFold(v string) predicate.Permission {
	return predicate.Permission(sql.FieldContainsFold(FieldObjectType, v))
}

// HasRoles applies the HasEdge predicate on the "roles" edge.
func HasRoles() predicate.Permission {
	return predicate.Permission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, RolesTable, RolesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRolesWith applies the HasEdge predicate on the "roles" edge with a given conditions (other predicates).
func HasRolesWith(preds ...predicate.Role) predicate.Permission {
	return predicate.Permission(func(s *sql.Selector) {
		step := newRolesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Permission) predicate.Permission {
	return predicate.Permission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Permission) predicate.Permission {
	return predicate.Permission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Permission) predicate.Permission {
	return predicate.Permission(sql.NotPredicates(p))
}
